# -*- coding: utf-8 -*-
"""
/***************************************************************************
 bankfullJBDialog
                                 A QGIS plugin
 This plugin estimates bankfull
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-20
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Brochier Juliette
        email                : juliettebrochier69@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pyproj
import pygeoops

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5 import QtCore, QtWidgets
from qgis.gui import QgsFileWidget, QgsProjectionSelectionWidget
from qgis.PyQt import uic
from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsMapLayerType,
    QgsWkbTypes,
    QgsApplication,
    QgsCoordinateReferenceSystem,
)

from shapely.geometry import Point, LineString
from shapely import reverse
from shapely.ops import linemerge
from shapely.wkb import loads as load_wkb
from scipy.interpolate import interp1d, make_interp_spline
from scipy.signal import find_peaks
from .calcul_aires import calculer_aire
from .calcul_prof_hydr import CalculerProfHydr
from .export_dataframe import export_data
from .lissage_savitzky_golay import curve_Savitzky_Golay
from .prof_hydr_bankfull_methods import find_bankfull_M1, find_bankfull_M2
from .echantillonner_MNT import ProjectionMNT
from .transects import CalculTransects
from .smooth_peaks import CalculerPeaks

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "bankfull_module_JB_dialog_base.ui")
)


class bankfullJBDialog(QtWidgets.QDialog, FORM_CLASS):

    def __init__(self, parent=None):
        """Constructor."""
        super().__init__(parent)
        self.setupUi(self)

        self.update_MNT_layers()
        self.update_polygon_layers()

        self.comboBox_MNT.activated.connect(self.select_couche_MNT)
        self.comboBox_polygon.activated.connect(self.select_couche_polygon)

        # Définir le texte par défaut
        le_config = {
            self.lineEdit_l_transect: "40",
            self.lineEdit_e_transects: "30",
            self.lineEdit_filtrage_aires: "0.1",
            self.lineEdit_interp_nb_pts: "500",
            self.lineEdit_dist_max_min: "10",
        }
        for le, default_value in le_config.items():
            le.setText(default_value)
            le.setStyleSheet("color: #808080; font-style: italic;")
            # Connecter les signaux de modification de texte
            le.textChanged.connect(self.updateLineEdit)

        self.crs = pyproj.CRS.from_string(QgsProject.instance().crs().authid())
        qgis_crs = QgsCoordinateReferenceSystem()
        qgis_crs.createFromOgcWmsCrs(self.crs.to_string())

        self.directory_path = None
        self.all_projected_distances = None
        self.all_projected_altitudes = None
        self.dist_pic = None
        self.selected_points_data = []
        self.pts_limites_results_list = []
        self.coords_3D_list = []
        self.coords_3D_left_list = []
        self.coords_3D_right_list = []
        self.spline_results = []
        self.peaks_valleys_data = []

        self.sliders_label = {
            self.horizontalSlider_visualisation_transects: self.label_current_profile,
            self.verticalSlider_visualisation: self.label_current_profile_2,
            self.horizontalSlider_pic_curve: self.label_current_profile_3,
            self.horizontalSlider_final_results: self.label_current_profile_4,
        }
        self.init_sliders()
        # --------------------------------------------------------------------------------
        # Connexion des signals
        # --------------------------------------------------------------------------------
        self.mQgsFileWidget_folder.setStorageMode(QgsFileWidget.GetDirectory)
        self.mQgsFileWidget_folder.fileChanged.connect(self.handle_folder_change)

        self.mQgsProjectionSelectionWidget_crs.setCrs(qgis_crs)
        self.mQgsProjectionSelectionWidget_crs.crsChanged.connect(self.on_crs_changed)

        self.pushButton_CalculerCenterline.clicked.connect(self.calc_centerline)
        self.pushButton_CalculerTransects.clicked.connect(self.calc_transects)
        self.pushButton_Exporter_donnees.clicked.connect(self.export_donnees)
        self.pushButton_Exporter_donnees_curve.clicked.connect(
            self.export_donnees_curve
        )
        self.pushButton_CalculerAires.clicked.connect(self.calc_aires)
        self.pushButton_CalculerProfHydr.clicked.connect(self.calc_prof_hydr)
        self.pushButton_Tracer_prof_hydr.clicked.connect(self.tracer_prof_hydr)
        self.pushButton_tracer_transects.clicked.connect(self.tracer_transects)
        self.radioButton_previous_transect.clicked.connect(
            self.find_banfkull_previous_transects
        )
        self.radioButton_amplitude_max.clicked.connect(self.find_bankfull_max_amplitude)
        self.radioButton_prof_hydr_max_amplitude.clicked.connect(
            self.select_prof_hydr_max_amplitude
        )
        self.radioButton_prof_hydr_previous_transects.clicked.connect(
            self.select_prof_hydr_previous_transects
        )
        self.radioButton_curvature.clicked.connect(self.select_curvature)
        self.pushButton_tracer_pic_curve.clicked.connect(self.tracer_pic_curve)
        self.pushButton_exporter_points_limite.clicked.connect(
            self.exporter_points_limite
        )
        self.pushButton_calculer_coord_3D.clicked.connect(
            self.call_coord_points_limites
        )
        self.pushButton_pic_curve.clicked.connect(self.pic_curve)
        self.pushButton_conserver_pt.clicked.connect(self.conserver_point)

        # --------------------------------------------------------------------------------
        # Initialisation des slider pour la visualisation dans les fenêtres graphiques
        # --------------------------------------------------------------------------------
        self.horizontalSlider_visualisation_transects.valueChanged.connect(
            self.tracer_transects
        )
        self.verticalSlider_visualisation.valueChanged.connect(self.tracer_prof_hydr)
        self.horizontalSlider_pic_curve.valueChanged.connect(self.tracer_pic_curve)
        self.horizontalSlider_final_results.valueChanged.connect(
            self.visualize_final_results
        )

    # --------------------------------------------------------------------------------
    # Mise à jour du répertoire d'enregistrement et des QLabel
    # --------------------------------------------------------------------------------
    def init_sliders(self) -> None:
        value = 0
        for slider, label in self.sliders_label.items():
            slider.setValue(value)
            label.setText(f"Profil actuel : {value}")
            # signal
            slider.valueChanged.connect(self.update_current_profile_label)

    def handle_folder_change(self, folder_path: str) -> None:
        print("Répertoire sélectionné:", folder_path)
        self.directory_path = folder_path

    def update_current_profile_label(self, value):
        self.sliders_label[self.sender()].setText(f"Profil actuel : {value}")

    # --------------------------------------------------------------------------------
    # Mise à jour des LineEdit
    # --------------------------------------------------------------------------------
    def updateLineEdit(self):
        self.sender().setStyleSheet("color: black;")

    # --------------------------------------------------------------------------------
    # Import des couches (données de départ)
    # --------------------------------------------------------------------------------
    def update_MNT_layers(self):
        self.comboBox_MNT.clear()
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() == QgsMapLayerType.RasterLayer:
                self.comboBox_MNT.addItem(layer.name())

    def select_couche_MNT(self):
        layer_name = self.comboBox_MNT.currentText()
        self.selected_MNT_layer = QgsProject.instance().mapLayersByName(layer_name)[0]
        print("Couche raster:", self.selected_MNT_layer)

    def update_polygon_layers(self):
        self.comboBox_polygon.clear()
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() == QgsMapLayerType.VectorLayer:
                if layer.geometryType() == QgsWkbTypes.PolygonGeometry:
                    self.comboBox_polygon.addItem(layer.name())

    def select_couche_polygon(self):
        layer_name = self.comboBox_polygon.currentText()
        self.selected_polygon_layer = QgsProject.instance().mapLayersByName(layer_name)[
            0
        ]
        print("Couche polygone:", self.selected_polygon_layer)

    # --------------------------------------------------------------------------------
    # Système de coordonnées
    # --------------------------------------------------------------------------------
    def on_crs_changed(self, crs: QgsCoordinateReferenceSystem):
        print(f"SCR sélectionné: {crs.authid()}")
        self.crs = pyproj.CRS.from_string(crs.authid())

    # -----------------------------#
    # - PRETRAITEMENT DES DONNEES -#
    # -----------------------------#
    # ----------------------------------------------------------------------------------
    # -Calcul de la ligne centrale
    # ----------------------------------------------------------------------------------
    def calc_centerline(self, checked: bool) -> None:
        """Calcul de la ligne centrale du cours d'eau
        :param checked: checked est "True" si le bouton est appuyé
        """
        vector_layer = self.selected_polygon_layer

        # Extraction des géométries de la couche polygonale
        polygon = []

        for feature in vector_layer.getFeatures():
            geom = feature.geometry()
            wkb = geom.asWkb()
            shapely_geom = load_wkb(bytes(wkb))
            polygon.append(shapely_geom)

        # Utilisation du package pygeoops pour le calcul de la ligne centrale
        centerline = pygeoops.centerline(
            polygon, densify_distance=1, simplifytolerance=0.5
        )

        merged_centerline = reverse(linemerge(centerline))
        line_length = merged_centerline.length
        print(f"La longueur de la ligne est : {line_length}m")
        gdf_centerline = gpd.GeoDataFrame(
            {
                "geometry": [merged_centerline],
            },
            crs=self.crs,
        )

        # Export de la couche "ligne_centrale" dans un fichier GeoPackage
        output_path = os.path.join(self.directory_path, "ligne_centrale.gpkg")
        gdf_centerline.to_file(output_path, driver="GPKG")

        # Ajout de la couche "ligne_centrale" au projet
        if not gdf_centerline.empty:
            print("Export réussi:", output_path)
            layer = QgsVectorLayer(output_path, "ligne_centrale", "ogr")
            if not layer.isValid():
                print("La couche n'est pas valide.")
                return
            QgsProject.instance().addMapLayer(layer)
            print("Fichier ligne_centrale.gpkg ajouté dans le projet avec succès")

        else:
            print("Géométrie vide")

    # ----------------------------------------------------------------------------------
    # -Calcul des transects perpendiculairement à la ligne centrale
    # ----------------------------------------------------------------------------------
    def calc_transects(self):
        """Calcul des profils en travers perpendiculairement à la ligne centrale"""
        # Récupération des valeurs des QLabel
        transect_length = float(self.lineEdit_l_transect.text())  # longueur du profil
        transect_spacing = float(self.lineEdit_e_transects.text())  # pas d'espacement
        CalculTransects(
            transect_length, transect_spacing, self.directory_path, self.crs
        )

    # ----------------------------------------------------------------------------------
    # - Projection des transects sur le MNT
    # ----------------------------------------------------------------------------------
    def projection_mnt(self):
        """Projection des profils sur le MNT"""
        # Couche des profils
        transect_layers = [
            layer
            for layer in QgsProject.instance().mapLayers().values()
            if layer.name() == "profils"
            and layer.source().startswith(self.directory_path)
        ]
        # Couche de la ligne centrale
        centerline_layers = [
            layer
            for layer in QgsProject.instance().mapLayers().values()
            if layer.name() == "ligne_centrale"
            and layer.source().startswith(self.directory_path)
        ]
        # Couche du MNT
        selected_MNT_layer = self.selected_MNT_layer
        # Longueur des profils
        transect_length = float(self.lineEdit_l_transect.text())

        # Appel de la fonction qui récupère les informations de chaque profil
        df_transects = ProjectionMNT(
            transect_layers,
            centerline_layers,
            transect_length,
            selected_MNT_layer,
        )
        return df_transects

    def export_donnees(self, checked: bool) -> None:
        """Export des données brutes
        :param checked: checked est "True" si le bouton est appuyé
        """
        df_transects = self.projection_mnt()
        output_file_name = "cross_section_data.csv"
        export_data(df_transects, self.directory_path, output_file_name)

    def export_donnees_curve(self, checked: bool) -> None:
        """Export des données de courbure
        :param checked: checked est "True" si le bouton est appuyé
        """
        df_transects = self.projection_mnt()
        output_file_name = "curve_data.csv"
        export_data(df_transects, self.directory_path, output_file_name)

    # ----------------------------------------------------------------------------------
    # - Visualisation des transects dans la graphicsView
    # ----------------------------------------------------------------------------------
    def tracer_transects(self):
        """Visualitsation des profils dans une genêtre graphique"""
        # Charger les données à partir du fichier CSV
        cross_section_data = pd.read_csv(
            os.path.join(self.directory_path, "cross_section_data.csv")
        )
        # Récupération de la valeur actuelle de la barre de défilement
        scrollbar_value_transects = (
            self.horizontalSlider_visualisation_transects.value()
        )

        # Calcul du nombre de graphiques visibles en fonction de la hauteur
        # de la GraphicsView et de la hauteur d'un graphique
        view_height = self.graphicsView_transects.height()
        graph_height = view_height
        visible_graphs = int(view_height / graph_height)
        # Déterminer l'indice de début en fonction
        # de la valeur de la barre de défilement
        start_index = scrollbar_value_transects
        end_index = start_index + visible_graphs
        # Grouper par 'x_sec_id'
        grouped_data = cross_section_data.groupby("x_sec_id")
        # Création de la scène
        scene_transects = QtWidgets.QGraphicsScene()

        # Boucle sur les groupes de données pour créer
        # les graphiques uniquement pour les indices visibles
        for group_name, group_data in grouped_data:
            # Vérifier si l'indice actuel est dans la plage visible
            if start_index <= group_name < end_index:
                # Création d'un widget pour le graphique
                graph_widget = QtWidgets.QWidget()
                layout = QtWidgets.QVBoxLayout(graph_widget)
                # Création du graphique matplotlib
                fig, ax = plt.subplots()
                altitude = group_data["POINT_Z"].to_numpy()
                distance = group_data["Distance"].to_numpy()
                ax.set_facecolor((0.56, 0.93, 0.56, 0.10))
                ax.scatter(distance, altitude, color="black", s=2)
                ax.set_title(
                    f"Profil en travers n°{group_name}", fontsize=11, weight="bold"
                )
                ax.set_xlabel("Distance (m)", fontsize=11)
                ax.set_ylabel("Altitude (m)", fontsize=11)
                ax.grid(True)
                plt.tight_layout()
                # Ajout du graphique à la scène
                layout.addWidget(FigureCanvas(fig))
                scene_transects.addWidget(graph_widget)
                break

        # Affichage de la scène dans la QGraphicsView
        self.graphicsView_transects.setScene(scene_transects)
        self.graphicsView_transects.fitInView(
            scene_transects.sceneRect(), QtCore.Qt.KeepAspectRatio
        )

    # -----------------------------------------------#
    # - METHODES DE CALCUL DU NIVEAU A PLEINS BORDS -#
    # -----------------------------------------------#
    # ----------------------------------------------------------------------------------
    # - Méthode 1 basée sur la profondeur hydraulique
    # ----------------------------------------------------------------------------------

    # 0. Définition de la fonction d'appel reliée au pushButton_CalculerAires
    def calc_aires(self) -> None:
        """Génération d'une DataFrame contenant les informations
        des aires entre deux courbes"""

        # Données des profils en travers
        cross_section_data = pd.read_csv(
            os.path.join(self.directory_path, "cross_section_data.csv")
        )
        cross_section_data["POINT_Z"] = cross_section_data["POINT_Z"].apply(
            lambda x: round(x, 3)
        )

        # QLineEdit contenant le critère de filtrage des aires en m²
        filtrage_aires = float(self.lineEdit_filtrage_aires.text())

        # Groupement des données par transect
        grouped_data = cross_section_data.groupby("x_sec_id")

        results_list = []
        # Stocker les résultats dans une liste de dictionnaires
        for x_sec_id, data_group in grouped_data:
            # Suppression des doublons d'altitudes
            unique_data_group = data_group.drop_duplicates(subset=["POINT_Z"])
            unique_data_group.reset_index(drop=True, inplace=True)
            alti = unique_data_group["POINT_Z"].values
            alti_ref = sorted(alti)
            dist = unique_data_group["Distance"].values

            # Calcul des aires du profil i
            areas_iteration = calculer_aire(dist, alti, alti_ref, filtrage_aires)

            # Résultats dans une liste de dictionnaire
            for (
                iteration,
                areas,
                distances,
                ref_altitude,
                intersection_indices_list,
            ) in areas_iteration:
                for i, (area, classification, ref_altitude) in enumerate(areas):
                    # Modifier le signe des aires en fonction de la classification
                    modified_area = area if classification == "above" else -area

                    # Dictionnaire pour chaque aire avec les informations requises
                    result_dict = {
                        "x_sec_id": x_sec_id,
                        "iteration": iteration,
                        "area": modified_area,
                        "distance_between_intersections": distances[i],
                        "ref_altitude": ref_altitude,
                    }
                    results_list.append(result_dict)

        # Créer un DataFrame à partir de la liste de dictionnaires
        results_df = pd.DataFrame(results_list)
        df_output_path = os.path.join(self.directory_path, "area_trapezes.csv")
        results_df.to_csv(df_output_path, sep=",", index=False)
        print("Fichier .csv 'area_trapezes.csv' exporté avec succès.")

    # 1. Calcul de l'indicateur de profondeur hydraulique pour chaque
    # altitude présente dans la liste de référence
    def calc_prof_hydr(self):
        area_trapezes_data = pd.read_csv(
            os.path.join(self.directory_path, "area_trapezes.csv")
        )
        largest_negative_area = CalculerProfHydr(area_trapezes_data)
        output_file = os.path.join(self.directory_path, "prof_hydr.csv")
        largest_negative_area.to_csv(output_file, index=False)
        print("DataFrame exporté avec succès vers", output_file)

    # Lissage de la courbe de profondeur hydraulique en fonction de l'altitude
    # Détection des minimums et maximums locaux
    def smooth_peaks(self):
        dist_pic = int(float(self.lineEdit_dist_max_min.text()))
        pts_interp = int(float(self.lineEdit_interp_nb_pts.text()))
        spline_results, peaks_valleys_data = CalculerPeaks(
            dist_pic, pts_interp, self.directory_path
        )
        return spline_results, peaks_valleys_data

    # Fonction pour visualiser la courbe lissée et les maximums/minimums locaux
    def tracer_prof_hydr(self) -> None:
        # Charger les données à partir du fichier CSV
        prof_hydr_data = pd.read_csv(os.path.join(self.directory_path, "prof_hydr.csv"))
        dist_pic = int(float(self.lineEdit_dist_max_min.text()))
        pts_interp = int(float(self.lineEdit_interp_nb_pts.text()))
        spline_results, peaks_valleys_data = CalculerPeaks(
            dist_pic, pts_interp, self.directory_path
        )

        # Récupération de la valeur de la barre de défilement
        scrollbar_value = self.verticalSlider_visualisation.value()
        view_height = self.graphicsView_prof_hydr.height()
        graph_height = view_height
        # Graphique visible en focntion de la hauteur de la vue
        visible_graphs = max(1, int(view_height / graph_height))

        start_index = scrollbar_value
        end_index = start_index + visible_graphs

        # Grouper par 'x_sec_id'
        grouped_data = prof_hydr_data.groupby("x_sec_id")

        # Création de la scène
        scene = QtWidgets.QGraphicsScene()

        for group_name, group_data in grouped_data:
            if start_index <= group_name < end_index:
                graph_widget = QtWidgets.QWidget()
                layout = QtWidgets.QVBoxLayout(graph_widget)

                # Création d'une figure
                fig, ax = plt.subplots()
                ax.set_facecolor((0.68, 0.85, 0.90, 0.10))
                ref_altitude = group_data["ref_altitude"].to_numpy()
                profondeur_hydraulique = group_data["profondeur_hydraulique"].to_numpy()
                ax.scatter(ref_altitude, profondeur_hydraulique, color="#236B8E", s=2)
                ax.set_title(
                    f"Profondeur hydraulique en fonction" f" de l'altitude",
                    fontsize=11,
                )
                ax.set_xlabel("Altitude (m)", fontsize=11)
                ax.set_ylabel("Profondeur Hydraulique", fontsize=11)
                ax.grid(True)

                # Find corresponding spline results
                for result in spline_results:
                    if result[0] == group_name:
                        x_smooth = np.array(result[1])
                        y_smooth = np.array(result[2])
                        break

                # Tracé de la courbe lissée
                ax.plot(
                    x_smooth,
                    y_smooth,
                    linestyle="-",
                    color="#236B8E",
                )

                # Tracé des maximums/minimums locaux
                peaks_indices = [
                    idx
                    for idx, data in enumerate(peaks_valleys_data)
                    if data[0] == group_name and data[3] == "Maximum local"
                ]
                valleys_indices = [
                    idx
                    for idx, data in enumerate(peaks_valleys_data)
                    if data[0] == group_name and data[3] == "Minimum local"
                ]

                ax.scatter(
                    [peaks_valleys_data[idx][1] for idx in peaks_indices],
                    [peaks_valleys_data[idx][2] for idx in peaks_indices],
                    color="red",
                    marker="o",
                    label="Maximum local",
                )
                ax.scatter(
                    [peaks_valleys_data[idx][1] for idx in valleys_indices],
                    [peaks_valleys_data[idx][2] for idx in valleys_indices],
                    color="blue",
                    marker="o",
                    label="Minimum local",
                )

                ax.legend()
                plt.tight_layout()

                # Ajout du graphique à la scène
                layout.addWidget(FigureCanvas(fig))
                scene.addWidget(graph_widget)
                break

        # Affichage de la scène dans la QGraphicsView
        self.graphicsView_prof_hydr.setScene(scene)
        self.graphicsView_prof_hydr.fitInView(
            scene.sceneRect(), QtCore.Qt.KeepAspectRatio
        )

    # --------------------------------------------------------------------------------
    # Méthode 1a : Amplitude de rupture de pente maximale
    # --------------------------------------------------------------------------------
    def find_bankfull_max_amplitude(self):
        find_bankfull_M1(self.spline_results, self.directory_path, self.dist_pic)
        # print("Altitudes de débordement:", bankfull_values_M1)

    # --------------------------------------------------------------------------------
    # Méthode 1b : Profils précédents
    # --------------------------------------------------------------------------------
    def find_banfkull_previous_transects(self):
        find_bankfull_M2(self.spline_results, self.directory_path, self.dist_pic)

    # --------------------------------------------------------------------------------
    # Méthode 2 basée sur la courbure minimale du relief
    # --------------------------------------------------------------------------------

    # 1. Détection des pic sur la courbe de courbure en fonction de la distance
    def pic_curve(self):
        curve_data = pd.read_csv(
            os.path.join(self.directory_path, "curve_data.csv"), sep=","
        )
        cross_section_data = pd.read_csv(
            os.path.join(self.directory_path, "cross_section_data.csv"), sep=","
        )
        # Appliquer le lissage Savitzky-Golay aux données de courbure
        self.transect_data = curve_Savitzky_Golay(curve_data, cross_section_data)

    # 2. Affichage des courbes lissées avec les divers pics sélectionnés
    def tracer_pic_curve(self):
        cross_section_data = pd.read_csv(
            os.path.join(self.directory_path, "cross_section_data.csv"), sep=","
        )
        alti_bankfull_m1 = pd.read_csv(
            os.path.join(self.directory_path, "bankfull_max_amplitude.csv"), sep=","
        )
        alti_bankfull_m2 = pd.read_csv(
            os.path.join(self.directory_path, "bankfull_previous_transects.csv"),
            sep=",",
        )

        # Récupération de la valeur de la barre de défilement
        scrollbar_value = self.horizontalSlider_pic_curve.value()

        # Calcul du nombre de graphiques visibles
        view_height = self.graphicsView_pic_curve.height()
        graph_height = view_height
        visible_graphs = max(1, int(view_height / graph_height))
        start_index = scrollbar_value
        end_index = start_index + visible_graphs

        # Création de la scène
        scene = QtWidgets.QGraphicsScene()

        # Réinitialiser la liste des points annotés
        self.annotated_points = []

        for transect_id, projected_distances, projected_altitudes in self.transect_data:
            # Vérifier si l'indice actuel est dans la plage visible
            if start_index <= transect_id < end_index:
                # Création d'un widget pour le graphique
                graph_widget = QtWidgets.QWidget()
                layout = QtWidgets.QVBoxLayout(graph_widget)

                # Création du graphique matplotlib
                fig, ax = plt.subplots(figsize=(8, 6))
                ax.set_facecolor((0.85, 0.85, 0.85, 0.10))
                alti = cross_section_data[
                    cross_section_data["x_sec_id"] == transect_id
                ]["POINT_Z"].to_numpy()
                distance = cross_section_data[
                    cross_section_data["x_sec_id"] == transect_id
                ]["Distance"].to_numpy()

                # Tracé de la courbe de courbure et des pics détectés
                ax.plot(
                    distance, alti, label="Profil en travers", zorder=1, color="#4F4F2F"
                )
                ax.scatter(
                    projected_distances,
                    projected_altitudes,
                    color="red",
                    s=20,
                    zorder=2,
                )

                # Annoter chaque point avec un numéro unique
                for i, (dist, alt) in enumerate(
                    zip(projected_distances, projected_altitudes)
                ):
                    point_label = f"{i}"
                    dist = round(dist, 2)
                    alt = round(alt, 2)
                    ax.annotate(
                        point_label,
                        (dist, alt),
                        textcoords="offset points",
                        xytext=(5, 5),
                        ha="center",
                        fontsize=7,
                        color="black",
                    )
                    self.annotated_points.append((transect_id, i, dist, alt))

                # Ajouter les lignes horizontales pour les altitudes de débordement
                bankfull_m1 = alti_bankfull_m1[
                    alti_bankfull_m1["x_sec_id"] == transect_id
                ]["altitude"].values
                bankfull_m2 = alti_bankfull_m2[
                    alti_bankfull_m2["x_sec_id"] == transect_id
                ]["altitude"].values

                if bankfull_m1.size > 0:
                    ax.axhline(
                        y=bankfull_m1[0],
                        color="#E47833",
                        linestyle="-.",
                        label="Amplitude maximale",
                    )
                if bankfull_m2.size > 0:
                    ax.axhline(
                        y=bankfull_m2[0],
                        color="#99CC32",
                        linestyle="-.",
                        label="Profils précédents",
                    )

                ax.set_title(
                    "Profil en travers avec les points détectés",
                    fontsize=11,
                )
                ax.set_xlabel("Distance (m)")
                ax.set_ylabel("Altitude (m)")
                ax.legend()
                ax.grid(True)
                plt.tight_layout()

                # Ajout du graphique à la scène
                layout.addWidget(FigureCanvas(fig))
                scene.addWidget(graph_widget)

        # Affichage de la scène dans la QGraphicsView
        self.graphicsView_pic_curve.setScene(scene)
        self.graphicsView_pic_curve.fitInView(
            scene.sceneRect(), QtCore.Qt.KeepAspectRatio
        )

        # Exporter les données conservées vers un fichier CSV
        if self.selected_points_data:
            self.exporter_dataframe_csv("selected_points_data.csv")

    # 3. Choix de l'altitude de débordement avec sélection
    # du point retenu par l'utilisateur pour chaque transect
    def conserver_point(self):
        point_index_str = self.lineEdit_id_pt_conserver.text()
        try:
            point_index = int(point_index_str)

            # Utiliser le premier transect visible comme référence
            transect_id = self.horizontalSlider_pic_curve.value()

            # Recherche du point dans la liste des points annotés
            for point in self.annotated_points:
                if point[0] == transect_id and point[1] == point_index:
                    print(
                        f"Point conservé : Transect ID = {transect_id}, Point Index = {point_index}, Distance = {point[2]}, Altitude = {point[3]}"
                    )
                    # Stocker les informations du point conservé dans la liste
                    self.selected_points_data.append(
                        {
                            "x_sec_id": transect_id,
                            "point_index": point_index,
                            "distance": point[2],
                            "altitude": point[3],
                        }
                    )
                    return

            print("Point non trouvé. Veuillez vérifier l'identifiant du point.")
        except ValueError:
            print(
                "Identifiant du point invalide. Veuillez entrer un identifiant au format correct."
            )

    def exporter_dataframe_csv(self, filename):
        # Créer un DataFrame à partir de la liste des points conservés
        df_selected_points = pd.DataFrame(self.selected_points_data)
        # Construire le chemin complet pour le fichier CSV
        filepath = os.path.join(self.directory_path, filename)
        # Exporter le DataFrame au format CSV
        df_selected_points.to_csv(filepath, index=False)

    # --------------------------------------------------------------------------------
    # Visualisation des résultats dans une fenêtre graphique
    # --------------------------------------------------------------------------------
    selected_algorithm = None

    def select_prof_hydr_max_amplitude(self):
        self.selected_algorithm = "prof_hydr_max_amplitude"
        self.visualize_final_results()

    def select_prof_hydr_previous_transects(self):
        self.selected_algorithm = "prof_hydr_previous_transects"
        self.visualize_final_results()

    def select_curvature(self):
        self.selected_algorithm = "curvature"
        self.visualize_final_results()

    def visualize_final_results(self):
        """Visualisation des résultats en fonction de la méthode utilisée"""
        if self.selected_algorithm is None:
            # Si aucun algorithme n'est sélectionné, ne rien faire
            return
        algorithm_info = {
            "prof_hydr_max_amplitude": {
                "data_bankfull": "bankfull_max_amplitude.csv",
                "cross_section_data": "cross_section_data.csv",
                "final_results_function": self.final_results_prof_hydr,
            },
            "prof_hydr_previous_transects": {
                "data_bankfull": "bankfull_previous_transects.csv",
                "cross_section_data": "cross_section_data.csv",
                "final_results_function": self.final_results_prof_hydr,
            },
            "curvature": {
                "data_bankfull": "selected_points_data.csv",
                "cross_section_data": "cross_section_data.csv",
                "final_results_function": self.final_results_curvature,
            },
        }

        algorithm_data = algorithm_info.get(self.selected_algorithm)
        if algorithm_data:
            data_path = algorithm_data.get("data_bankfull")
            cross_section_data_path = algorithm_data.get("cross_section_data")
            final_results_function = algorithm_data.get("final_results_function")

            if data_path and cross_section_data_path:
                data_bankfull = pd.read_csv(
                    os.path.join(self.directory_path, data_path), sep=","
                )
                cross_section_data = pd.read_csv(
                    os.path.join(self.directory_path, cross_section_data_path), sep=","
                )
                final_results_function(data_bankfull, cross_section_data)

    def interpolate_coordinates(
        self, x_values, y_values, altitude_values, target_altitude
    ):
        # Effectuer l'interpolation des coordonnées x et y en fonction de l'altitude
        interpolation_function_x = interp1d(altitude_values, x_values)
        interpolation_function_y = interp1d(altitude_values, y_values)

        # Calculer les coordonnées interpolées pour l'altitude cible
        x_interpolated = interpolation_function_x(target_altitude)
        y_interpolated = interpolation_function_y(target_altitude)

        return x_interpolated, y_interpolated

    def final_results_prof_hydr(self, data_bankfull, cross_section_data):
        cross_section_data = pd.read_csv(
            os.path.join(self.directory_path, "cross_section_data.csv"), sep=","
        )

        scrollbar_value = self.horizontalSlider_final_results.value()
        view_height = self.graphicsView_prof_hydr.height()
        graph_height = 541  # Hauteur approximative d'un graphique
        visible_graphs = max(1, int(view_height / graph_height))

        start_index = scrollbar_value
        end_index = start_index + visible_graphs

        x_sec_id_unique = cross_section_data["x_sec_id"].unique()

        alti_bankfull_dict = {}

        self.pts_limites_results_list = []

        for x_sec_id in x_sec_id_unique:
            alti_bankfull_dict[x_sec_id] = data_bankfull[
                data_bankfull["x_sec_id"] == x_sec_id
            ]["altitude"].values[0]

        for group_name, group_data in cross_section_data.groupby("x_sec_id"):
            bankfull_altitude = alti_bankfull_dict[group_name]
            alti = group_data["POINT_Z"].to_numpy()
            distance = group_data["Distance"].to_numpy()

            # Trouver les coordonnées de la droite d'altitude de débordement
            river_center_distance = round(
                group_data[group_data["RivCentre"] == True]["Distance"].iloc[0], 3
            )
            bankfull_point_y = bankfull_altitude

            # Calculer les points d'intersection entre la droite et le profil
            left_intersection = None
            right_intersection = None

            # Trouver le premier point d'intersection à gauche
            for i in range(len(distance) - 1, -1, -1):
                if distance[i] < river_center_distance:
                    if alti[i] >= bankfull_point_y:
                        left_intersection = (distance[i], bankfull_point_y)
                        break

            # Trouver le premier point d'intersection à droite
            for i in range(len(distance)):
                if distance[i] >= river_center_distance:
                    if alti[i] >= bankfull_point_y:
                        right_intersection = (distance[i], bankfull_point_y)
                        break

            # Ajouter les résultats à la liste
            self.pts_limites_results_list.append(
                (group_name, left_intersection, right_intersection)
            )

        # Création de la scène
        scene = QtWidgets.QGraphicsScene()

        # Boucle sur les groupes de données pour créer les graphiques uniquement pour les indices visibles
        for group_name, group_data in cross_section_data.groupby("x_sec_id"):
            # Vérifier si l'indice actuel est dans la plage visible
            if start_index <= group_name < end_index:

                graph_widget = QtWidgets.QWidget()
                layout = QtWidgets.QVBoxLayout(graph_widget)
                bankfull_altitude = alti_bankfull_dict[group_name]

                # Création du graphique
                fig, ax = plt.subplots(figsize=(8, 6))  # Taille du graphique
                alti = group_data["POINT_Z"].to_numpy()
                distance = group_data["Distance"].to_numpy()
                ax.plot(distance, alti, label="Profil en travers")
                ax.set_title(
                    f"Profil en travers avec altitude de débordement (profil {group_name})",
                    fontsize=11,
                )
                ax.set_xlabel("Distance (m)", fontsize=11)
                ax.set_ylabel("Altitude (m)", fontsize=11)
                ax.grid(True)

                # Tracer la droite d'altitude de débordement
                ax.axhline(
                    y=bankfull_altitude,
                    color="r",
                    linestyle="--",
                    linewidth=1,
                    label=f"Altitude de débordement: {bankfull_altitude:.2f}",
                )

                # Afficher les points d'intersection
                left_intersection = next(
                    (
                        item[1]
                        for item in self.pts_limites_results_list
                        if item[0] == group_name
                    ),
                    None,
                )
                right_intersection = next(
                    (
                        item[2]
                        for item in self.pts_limites_results_list
                        if item[0] == group_name
                    ),
                    None,
                )

                if left_intersection:
                    ax.plot(
                        left_intersection[0],
                        left_intersection[1],
                        "bo",
                        label="Point limite gauche",
                    )
                if right_intersection:
                    ax.plot(
                        right_intersection[0],
                        right_intersection[1],
                        "go",
                        label="Point limite droite",
                    )

                ax.legend()
                plt.tight_layout()

                # Ajouter le graphique à la scène
                layout.addWidget(FigureCanvas(fig))
                scene.addWidget(graph_widget)

        # Afficher la scène dans la QGraphicsView
        self.graphicsView_final_results.setScene(scene)
        self.graphicsView_final_results.fitInView(
            scene.sceneRect(), QtCore.Qt.KeepAspectRatio
        )

        print(self.pts_limites_results_list)

        return self.pts_limites_results_list

    def final_results_curvature(self, data_bankfull, cross_section_data):
        selected_points_data = pd.read_csv(
            os.path.join(self.directory_path, "selected_points_data.csv"), sep=","
        )

        scrollbar_value = self.horizontalSlider_final_results.value()
        view_height = self.graphicsView_prof_hydr.height()
        graph_height = 541  # Hauteur approximative d'un graphique
        visible_graphs = max(1, int(view_height / graph_height))
        start_index = scrollbar_value
        end_index = start_index + visible_graphs

        scene = QtWidgets.QGraphicsScene()

        x_sec_id_unique = cross_section_data["x_sec_id"].unique()

        alti_bankfull_dict = {}
        self.pts_limites_results_list = []

        for x_sec_id in x_sec_id_unique:
            alti_bankfull_dict[x_sec_id] = data_bankfull[
                data_bankfull["x_sec_id"] == x_sec_id
            ]["altitude"].values[0]

        for group_name, group_data in cross_section_data.groupby("x_sec_id"):
            alti = group_data["POINT_Z"].to_numpy()
            distance = group_data["Distance"].to_numpy()

            # Trouver la berge la plus basse
            river_center = group_data[group_data["RivCentre"] == True]

            # Déterminer la berge contenant le point sélectionné
            selected_point = selected_points_data[
                selected_points_data["x_sec_id"] == group_name
            ]
            if not selected_point.empty:
                selected_point_distance = selected_point["distance"].iloc[0]
                selected_point_altitude = selected_point["altitude"].iloc[0]
                river_center_distance = river_center.iloc[0]["Distance"]

                if selected_point_distance < river_center_distance:
                    selected_bank = "gauche"
                else:
                    selected_bank = "droite"

                # Calculer les points d'intersection sur l'autre berge
                other_bank_intersection = None

                if selected_bank == "gauche":
                    # Trouver le premier point d'intersection à droite
                    for i in range(len(distance)):
                        if (
                            distance[i] >= river_center_distance
                            and alti[i] >= selected_point_altitude
                        ):
                            other_bank_intersection = (
                                distance[i],
                                selected_point_altitude,
                            )
                            break
                else:
                    # Trouver le premier point d'intersection à gauche
                    for i in range(len(distance) - 1, -1, -1):
                        if (
                            distance[i] < river_center_distance
                            and alti[i] >= selected_point_altitude
                        ):
                            other_bank_intersection = (
                                distance[i],
                                selected_point_altitude,
                            )
                            break

                left_intersection = None
                right_intersection = None

                if selected_point_distance < river_center_distance:
                    left_intersection = (
                        selected_point_distance,
                        selected_point_altitude,
                    )
                else:
                    right_intersection = (
                        selected_point_distance,
                        selected_point_altitude,
                    )

                if selected_bank == "gauche" and other_bank_intersection:
                    right_intersection = other_bank_intersection
                elif selected_bank == "droite" and other_bank_intersection:
                    left_intersection = other_bank_intersection

                # Ajouter les résultats à la liste
                self.pts_limites_results_list.append(
                    (group_name, left_intersection, right_intersection)
                )

        # Boucle sur les groupes de données pour créer les graphiques uniquement pour les indices visibles
        for group_name, group_data in cross_section_data.groupby("x_sec_id"):
            # Vérifier si l'indice actuel est dans la plage visible
            if start_index <= group_name < end_index:
                # Création d'un widget pour le graphique
                graph_widget = QtWidgets.QWidget()
                layout = QtWidgets.QVBoxLayout(graph_widget)

                # Création du graphique
                fig, ax = plt.subplots(figsize=(8, 6))  # Taille du graphique
                alti = group_data["POINT_Z"].to_numpy()
                distance = group_data["Distance"].to_numpy()
                ax.plot(distance, alti, label="Profil en travers")

                # Recherche du point sélectionné pour ce profil
                selected_point = selected_points_data[
                    selected_points_data["x_sec_id"] == group_name
                ]
                if not selected_point.empty:
                    # Tracer le point sélectionné
                    ax.scatter(
                        selected_point["distance"],
                        selected_point["altitude"],
                        color="red",
                        s=40,
                        label="Point conservé",
                    )
                    # Tracer une droite horizontale passant par le point sélectionné
                    ax.axhline(
                        y=selected_point["altitude"].iloc[0],
                        color="red",
                        linestyle="--",
                        label=f'Altitude conservé: {selected_point["altitude"].iloc[0]}',
                    )

                    # Tracer les points d'intersection
                    for result in self.pts_limites_results_list:
                        if result[0] == group_name:
                            conserved_point = result[1]
                            other_bank_intersection = result[2]
                            if conserved_point and conserved_point != (
                                selected_point["distance"].iloc[0],
                                selected_point["altitude"].iloc[0],
                            ):
                                ax.scatter(
                                    conserved_point[0],
                                    conserved_point[1],
                                    color="red",
                                    s=40,
                                    label="Point conservé",
                                )
                            if other_bank_intersection:
                                ax.scatter(
                                    other_bank_intersection[0],
                                    other_bank_intersection[1],
                                    color="blue",
                                    s=40,
                                    label="Intersection autre berge",
                                )

                ax.set_title(
                    f"Profil en travers avec point conservé (transect {group_name})",
                    fontsize=11,
                )
                ax.set_xlabel("Distance", fontsize=11)
                ax.set_ylabel("Altitude", fontsize=11)
                ax.legend()
                ax.grid(True)
                plt.tight_layout()

                # Ajout du graphique à la scène
                layout.addWidget(FigureCanvas(fig))
                scene.addWidget(graph_widget)

        # Affichage de la scène dans la QGraphicsView
        self.graphicsView_final_results.setScene(scene)
        self.graphicsView_final_results.fitInView(
            scene.sceneRect(), QtCore.Qt.KeepAspectRatio
        )

        print(self.pts_limites_results_list)

        return self.pts_limites_results_list
    # --------------------------------------------------------------------------------------------------------
    # Calcul des points de la limite en fonction de la méthode retenue pour le choix du niveau de débordement
    # --------------------------------------------------------------------------------------------------------
    def call_coord_points_limites(self):
        pts_limites_results_list = self.pts_limites_results_list
        self.coord_points_limites(pts_limites_results_list)

    def coord_points_limites(self, pts_limites_results_list):
        cross_section_data = pd.read_csv(
            os.path.join(self.directory_path, "cross_section_data.csv"), sep=","
        )

        self.coords_3D_left_list = []
        self.coords_3D_right_list = []

        # Boucle pour transformer les coordonnées de chaque transect
        for transect_id, left_point, right_point in pts_limites_results_list:
            # Récupérer les données pour ce transect
            transect_data = cross_section_data[
                cross_section_data["x_sec_id"] == transect_id
            ]

            # Obtenir les coordonnées X, Y, et Z (altitude)
            distances = transect_data["Distance"].to_numpy()
            x_coords = transect_data["POINT_X"].to_numpy()
            y_coords = transect_data["POINT_Y"].to_numpy()

            # Fonction pour l'interpolation linéaire des coordonnées X et Y
            def interpolate_coords(distance, distances, x_coords, y_coords):
                x_interp = np.interp(distance, distances, x_coords)
                y_interp = np.interp(distance, distances, y_coords)
                return x_interp, y_interp

            # Interpoler les coordonnées pour le point limite droite
            if right_point:
                right_distance, right_altitude = right_point
                right_x, right_y = interpolate_coords(
                    right_distance, distances, x_coords, y_coords
                )
                self.coords_3D_right_list.append((right_x, right_y, right_altitude))

            # Interpoler les coordonnées pour le point limite gauche
            if left_point:
                left_distance, left_altitude = left_point
                left_x, left_y = interpolate_coords(
                    left_distance, distances, x_coords, y_coords
                )
                self.coords_3D_left_list.append(
                    (transect_id, left_x, left_y, left_altitude)
                )
        return self.coords_3D_left_list, self.coords_3D_right_list

    def exporter_points_limite(self):
        self.coord_points_limites(self.pts_limites_results_list)
        if self.selected_algorithm == "prof_hydr_max_amplitude":
            self.export_points_limite_prof_hydr_max_amplitude()
        elif self.selected_algorithm == "prof_hydr_previous_transects":
            self.export_points_limite_prof_hydr_previous_transects()
        elif self.selected_algorithm == "curvature":
            self.export_points_limite_curvature()

    def export_points_limites_shp(self, coords_3D_list, filename_prefix):
        # Export des points limites au format Shapefile
        filename = filename_prefix + ".shp"
        self.export_points_to_shapefile(coords_3D_list, filename)

    def export_points_to_shapefile(self, coords_3D_list, filename):
        output_shapefile_path = os.path.join(self.directory_path, filename)
        geometries = [Point(x, y, z) for _, x, y, z in coords_3D_list]
        transect_id, x_col, y_col, z_col = zip(
            *[(transect_id, x, y, z) for transect_id, x, y, z in coords_3D_list]
        )
        gdf = gpd.GeoDataFrame(
            {
                "id": transect_id,
                "x": x_col,
                "y": y_col,
                "z": z_col,
                "geometry": geometries,
            }
        )
        crs = {"init": "epsg:3948"}
        gdf.to_file(output_shapefile_path, crs=crs, geometry="geometry")
        print(f"Fichier Shapefile exporté avec succès : {output_shapefile_path}")

        layer = QgsVectorLayer(
            output_shapefile_path, os.path.splitext(filename)[0], "ogr"
        )
        if not layer.isValid():
            print("La couche n'est pas valide.")
        else:
            QgsProject.instance().addMapLayer(layer)
            print(
                f"Couche {os.path.splitext(filename)[0]} ajoutée au projet avec succès"
            )

    def export_points_limite_prof_hydr_max_amplitude(self):
        left_filename = "points_limite_prof_hydr_max_amplitude_left"
        right_filename = "points_limite_prof_hydr_max_amplitude_right"
        self.export_points_limites_shp(self.coords_3D_left_list, left_filename)
        self.export_points_limites_shp(self.coords_3D_right_list, right_filename)
        self.export_lines_between_points(
            self.coords_3D_left_list, "ligne_limite_gauche_prof_hydr_max_amplitude"
        )
        self.export_lines_between_points(
            self.coords_3D_right_list, "ligne_limite_droite_prof_hydr_max_amplitude"
        )

    def export_points_limite_prof_hydr_previous_transects(self):
        left_filename = "points_limite_prof_hydr_previous_transects_left"
        right_filename = "points_limite_prof_hydr_previous_transects_right"
        self.export_points_limites_shp(self.coords_3D_left_list, left_filename)
        self.export_points_limites_shp(self.coords_3D_right_list, right_filename)
        self.export_lines_between_points(
            self.coords_3D_left_list, "ligne_limite_gauche_prof_hydr_previous_transects"
        )
        self.export_lines_between_points(
            self.coords_3D_right_list,
            "ligne_limite_droite_prof_hydr_previous_transects",
        )

    def export_points_limite_curvature(self):
        left_filename = "points_limite_curvature_left"
        right_filename = "points_limite_curvature_right"
        self.export_points_limites_shp(self.coords_3D_left_list, left_filename)
        self.export_points_limites_shp(self.coords_3D_right_list, right_filename)
        self.export_lines_between_points(
            self.coords_3D_left_list, "limite_gauche_curvature"
        )
        self.export_lines_between_points(
            self.coords_3D_right_list, "ligne_limite_droite_curvature"
        )

    def export_lines_between_points(self, coords_3D_list, filename_prefix):
        lines = [LineString(coords_3D_list)]

        gdf = gpd.GeoDataFrame(geometry=lines)
        output_shapefile_path = os.path.join(
            self.directory_path, filename_prefix + ".shp"
        )
        crs = {"init": "epsg:3948"}
        gdf.to_file(output_shapefile_path, crs=crs)
        print(
            f"Fichier Shapefile de lignes exporté avec succès : {output_shapefile_path}"
        )

        layer = QgsVectorLayer(
            output_shapefile_path, os.path.splitext(filename_prefix)[0], "ogr"
        )
        if not layer.isValid():
            print("La couche de lignes n'est pas valide.")
        else:
            QgsProject.instance().addMapLayer(layer)
            print(
                f"Couche de lignes {os.path.splitext(filename_prefix)[0]} ajoutée au projet avec succès"
            )
