# -*- coding: utf-8 -*-
"""
/***************************************************************************
 bankfullJBDialog
                                 A QGIS plugin
 This plugin estimates bankfull
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-20
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Brochier Juliette
        email                : juliettebrochier69@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pyproj

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5 import QtCore, QtWidgets
from qgis.gui import QgsFileWidget
from qgis.PyQt import QtWidgets, uic
from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsPointXY,
    QgsGeometry,
    QgsMapLayer,
    QgsMapLayerType,
    QgsWkbTypes,
)
from shapely.geometry import *
from shapely.wkb import loads as load_wkb
from scipy.interpolate import interp1d
from .calcul_aires import calculer_aire
from .calcul_prof_hydr import CalculerProfHydr
from .calculate_centerline import calculate_centerline, clean_centerline
from .export_dataframe import export_data
from .lissage_courbe import LissageCourbe
from .lissage_savitzky_golay import curve_Savitzky_Golay
from .prof_hydr_bankfull_methods import find_bankfull_M1, find_bankfull_M2
from .projection_MNT import echantillonner_mnt, nearest_points_RivCentre
from .transects import CalculTransects

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "bankfull_module_JB_dialog_base.ui")
)


class bankfullJBDialog(QtWidgets.QDialog, FORM_CLASS):

    def __init__(self, parent=None):
        """Constructor."""
        super().__init__(parent)
        self.setupUi(self)
        self.update_MNT_layers()
        self.update_polygon_layers()
        self.comboBox_MNT.activated.connect(self.select_couche_MNT)
        self.comboBox_polygon.activated.connect(self.select_couche_polygon)
        self.directory_path = None
        self.all_projected_distances = None
        self.all_projected_altitudes = None
        self.selected_points_data = []
        self.pts_limites_results_list = []
        self.coords_3D_list = []

        self.sliders_label = {
            self.horizontalSlider_visualisation_transects: self.label_current_profile,
            self.verticalSlider_visualisation: self.label_current_profile_2,
            self.horizontalSlider_pic_curve: self.label_current_profile_3,
            self.horizontalSlider_final_results: self.label_current_profile_4,
        }
        self.init_sliders()
        # --------------------------------------------------------------------------------
        # Connexion des signals
        # --------------------------------------------------------------------------------
        self.mQgsFileWidget_folder.setStorageMode(QgsFileWidget.GetDirectory)
        self.mQgsFileWidget_folder.fileChanged.connect(self.handle_folder_change)
        self.pushButton_CalculerCenterline.clicked.connect(self.calc_centerline)
        self.pushButton_CalculerTransects.clicked.connect(self.calc_transects)
        self.pushButton_Exporter_donnees.clicked.connect(self.export_donnees)
        self.pushButton_Exporter_donnees_curve.clicked.connect(
            self.export_donnees_curve
        )
        self.pushButton_tracer_transects.clicked.connect(self.tracer_transects)
        self.pushButton_Tracer_prof_hydr.clicked.connect(self.tracer_prof_hydr)
        self.pushButton_Lisser_courbes.clicked.connect(self.lissage_spline)
        self.radioButton_prof_hydr_max_amplitude.clicked.connect(
            self.select_prof_hydr_max_amplitude
        )
        self.radioButton_prof_hydr_previous_transects.clicked.connect(
            self.select_prof_hydr_previous_transects
        )
        self.pushButton_pic_curve.clicked.connect(self.pic_curve)
        self.pushButton_tracer_pic_curve.clicked.connect(self.tracer_pic_curve)
        self.pushButton_conserver_pt.clicked.connect(self.conserver_point)

        # --------------------------------------------------------------------------------
        # Initialisation des slider pour la visualisation dans les fenêtres graphiques
        # --------------------------------------------------------------------------------
        self.horizontalSlider_visualisation_transects.valueChanged.connect(
            self.tracer_transects
        )
        self.verticalSlider_visualisation.valueChanged.connect(self.tracer_prof_hydr)
        self.horizontalSlider_pic_curve.valueChanged.connect(self.tracer_pic_curve)
        self.horizontalSlider_final_results.valueChanged.connect(
            self.visualize_final_results
        )

    # --------------------------------------------------------------------------------
    # Connexions appropriées chaque fois que l'utilisateur change d'onglet
    # --------------------------------------------------------------------------------
    def on_tab_changed(self, index):
        # self.pushButton_CalculerCenterline.clicked.connect(self.calc_centerline)
        self.pushButton_CalculerTransects.clicked.connect(self.calc_transects)
        self.pushButton_Exporter_donnees.clicked.connect(self.export_donnees)
        self.pushButton_Exporter_donnees_curve.clicked.connect(
            self.export_donnees_curve
        )
        self.pushButton_CalculerAires.clicked.connect(self.calc_aires)
        self.pushButton_CalculerProfHydr.clicked.connect(self.calc_prof_hydr)
        self.pushButton_Tracer_prof_hydr.clicked.connect(self.tracer_prof_hydr)
        self.pushButton_Lisser_courbes.clicked.connect(self.lissage_spline)
        self.pushButton_tracer_transects.clicked.connect(self.tracer_transects)
        self.radioButton_previous_transect.clicked.connect(
            self.find_banfkull_previous_transects
        )
        self.radioButton_amplitude_max.clicked.connect(self.find_bankfull_max_amplitude)
        self.radioButton_curvature.clicked.connect(self.select_curvature)
        self.pushButton_pic_curve.clicked.connect(self.pic_curve)
        self.pushButton_tracer_pic_curve.clicked.connect(self.tracer_pic_curve)
        self.pushButton_exporter_points_limite.clicked.connect(
            self.exporter_points_limite
        )
        self.pushButton_calculer_coord_3D.clicked.connect(
            self.call_coord_points_limites
        )

    # --------------------------------------------------------------------------------
    # Mise à jour du répertoire d'enregistrement et des QLabel
    # --------------------------------------------------------------------------------
    def init_sliders(self) -> None:
        value = 0
        for slider, label in self.sliders_label.items():
            slider.setValue(value)
            label.setText(f"Profil actuel : {value}")
            # signal
            slider.valueChanged.connect(self.update_current_profile_label)

    def handle_folder_change(self, folder_path: str) -> None:
        print("Répertoire sélectionné:", folder_path)
        self.directory_path = folder_path

    def update_current_profile_label(self, value):
        self.sliders_label[self.sender()].setText(f"Profil actuel : {value}")

    # --------------------------------------------------------------------------------
    # Import des couches (données de départ)
    # --------------------------------------------------------------------------------
    def update_MNT_layers(self):
        self.comboBox_MNT.clear()
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() == QgsMapLayerType.RasterLayer:
                self.comboBox_MNT.addItem(layer.name())

    def select_couche_MNT(self):
        layer_name = self.comboBox_MNT.currentText()
        self.selected_MNT_layer = QgsProject.instance().mapLayersByName(layer_name)[0]
        print("Couche raster:", self.selected_MNT_layer)

    def update_polygon_layers(self):
        self.comboBox_polygon.clear()
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() == QgsMapLayerType.VectorLayer:
                if layer.geometryType() == QgsWkbTypes.PolygonGeometry:
                    self.comboBox_polygon.addItem(layer.name())

    def select_couche_polygon(self):
        layer_name = self.comboBox_polygon.currentText()
        self.selected_polygon_layer = QgsProject.instance().mapLayersByName(layer_name)[
            0
        ]
        print("Couche polygone:", self.selected_polygon_layer)

    # -----------------------------#
    # - PRETRAITEMENT DES DONNEES -#
    # -----------------------------#
    # ----------------------------------------------------------------------------------
    # -Calcul de la ligne centrale
    # ----------------------------------------------------------------------------------
    def calc_centerline(self, checked: bool) -> None:
        """Calcul de la ligne centrale du cours d'eau
        :param checked: checked est "True" si le bouton est appuyé
        """
        # Définition du système de coorodnnées
        crs_epsg = 3948  # EPSG:3948
        crs = pyproj.CRS.from_epsg(crs_epsg)
        # Récupération de la couche polygonale sélectionnée
        vector_layer = self.selected_polygon_layer

        # Création d'une liste pour stocker les géométries Shapely
        geometries = []
        # Extraction des géométries de la couche polygonale
        for feature in vector_layer.getFeatures():
            geom = feature.geometry()
            wkb = geom.asWkb()
            shapely_geom = load_wkb(bytes(wkb))
            geometries.append(shapely_geom)

        # Création du GeoDataFrame à partir des géométries Shapely
        gdf = gpd.GeoDataFrame(geometry=geometries)
        # Appel de la nouvelle fonction pour calculer la ligne centrale
        centerline_gdf, lines_number = calculate_centerline(gdf)
        # Nettoyage de la ligne centrale
        merged_filtered_gdf, layer_path = clean_centerline(
            centerline_gdf, crs, self.directory_path
        )
        if not merged_filtered_gdf.empty:
            print("Export réussi:", layer_path)
            # Ajout de la couche directement au projet
            layer = QgsVectorLayer(layer_path, "clean_centerline", "ogr")
            if not layer.isValid():
                print("La couche n'est pas valide.")
                return
            QgsProject.instance().addMapLayer(layer)
            print("Fichier clean_centerline.shp ajouté dans le projet avec succès")
        else:
            print("Géométrie vide")

    # ----------------------------------------------------------------------------------
    # -Calcul des transects perpendiculairement à la ligne centrale
    # ----------------------------------------------------------------------------------
    def calc_transects(self):
        transect_length = float(self.lineEdit_l_transect.text())
        transect_spacing = float(self.lineEdit_e_transects.text())
        CalculTransects(transect_length, transect_spacing, self.directory_path)

    # ----------------------------------------------------------------------------------
    # - Projection des transects sur le MNT
    # ----------------------------------------------------------------------------------
    def projection_mnt(self):
        transect_layer = QgsProject.instance().mapLayersByName("transects")[0]
        centerline_layer = QgsProject.instance().mapLayersByName("clean_centerline")[0]
        mnt_layer = self.selected_MNT_layer
        pixelSizeX = mnt_layer.rasterUnitsPerPixelX()

        # Calculer le nombre de points en fonction de la
        # résolution et de la longueur des transects
        length = float(self.lineEdit_l_transect.text())
        nb_pts = int(length / pixelSizeX)
        print("Nombre de points interpolés le long des transects  :", nb_pts)

        points_transects = []

        for feature in transect_layer.getFeatures():
            geom = feature.geometry()
            transect_points = echantillonner_mnt(geom, mnt_layer, nb_pts)
            transect_num = feature.id()
            nearest_point_index, _ = nearest_points_RivCentre(
                centerline_layer, transect_points
            )
            # Création d'une liste contenant des booléens indiquant
            # si chaque point est le plus proche de la ligne centrale
            rivcentre_column = [
                i == nearest_point_index for i in range(len(transect_points))
            ]
            # Ajout d'une colonne 'RivCentre' remplie de
            # valeurs booléennes à la liste points_transects
            points_transects.extend(
                [
                    (transect_num, i, point[0], point[1], point[2], is_nearest)
                    for i, (point, is_nearest) in enumerate(
                        zip(transect_points, rivcentre_column)
                    )
                ]
            )

        # Création de la DataFrame df_transects à partir de la liste points_transects
        df_transects = pd.DataFrame(
            points_transects,
            columns=[
                "x_sec_id",
                "x_sec_order",
                "POINT_X",
                "POINT_Y",
                "POINT_Z",
                "RivCentre",
            ],
        )
        return df_transects

    def export_donnees(self, checked: bool) -> None:
        df_transects = self.projection_mnt()
        output_file_name = "cross_section_data.csv"
        export_data(df_transects, self.directory_path, output_file_name)

    def export_donnees_curve(self, checked: bool) -> None:
        df_transects = self.projection_mnt()
        output_file_name = "curve_data.csv"
        export_data(df_transects, self.directory_path, output_file_name)

    # ----------------------------------------------------------------------------------
    # - Visualisation des transects dans la graphicsView
    # ----------------------------------------------------------------------------------
    def tracer_transects(self):
        # Charger les données à partir du fichier CSV
        cross_section_data = pd.read_csv(
            os.path.join(self.directory_path, "cross_section_data.csv")
        )

        scrollbar_value_transects = (
            self.horizontalSlider_visualisation_transects.value()
        )

        # Calcul du nombre de graphiques visibles en fonction de la hauteur
        # de la GraphicsView et de la hauteur d'un graphique
        view_height = self.graphicsView_transects.height()
        graph_height = 250
        visible_graphs = int(view_height / graph_height)
        # Déterminer l'indice de début en fonction
        # de la valeur de la barre de défilement
        start_index = scrollbar_value_transects
        end_index = start_index + visible_graphs
        # Grouper par 'x_sec_id'
        grouped_data = cross_section_data.groupby("x_sec_id")
        # Création de la scène
        scene_transects = QtWidgets.QGraphicsScene()

        # Boucle sur les groupes de données pour créer
        # les graphiques uniquement pour les indices visibles
        for group_name, group_data in grouped_data:
            # Vérifier si l'indice actuel est dans la plage visible
            if start_index <= group_name < end_index:
                # print("Création du graphique pour le transect", group_name)

                # Création d'un widget pour le graphique
                graph_widget = QtWidgets.QWidget()
                layout = QtWidgets.QVBoxLayout(graph_widget)
                # Création du graphique matplotlib
                fig, ax = plt.subplots()
                altitude = group_data["POINT_Z"].to_numpy()
                distance = group_data["Distance"].to_numpy()
                ax.scatter(distance, altitude, color="blue", s=4)
                ax.set_title(f"Profil en travers (transect {group_name})", fontsize=11)
                ax.set_xlabel("Distance (m)", fontsize=11)
                ax.set_ylabel("Altitude (m)", fontsize=11)
                ax.grid(True)
                plt.tight_layout()
                # Ajout du graphique à la scène
                layout.addWidget(FigureCanvas(fig))
                scene_transects.addWidget(graph_widget)
                break

        # Affichage de la scène dans la QGraphicsView
        self.graphicsView_transects.setScene(scene_transects)
        self.graphicsView_transects.fitInView(
            scene_transects.sceneRect(), QtCore.Qt.KeepAspectRatio
        )

    # -----------------------------------------------#
    # - METHODES DE CALCUL DU NIVEAU A PLEINS BORDS -#
    # -----------------------------------------------#
    # ----------------------------------------------------------------------------------
    # - Méthode 1 basée sur la profondeur hydraulique
    # ----------------------------------------------------------------------------------

    # 0. Définition de la fonction d'appel reliée au pushButton_CalculerAires
    def calc_aires(self) -> None:
        cross_section_data = pd.read_csv(
            os.path.join(self.directory_path, "cross_section_data.csv")
        )
        cross_section_data["POINT_Z"] = cross_section_data["POINT_Z"].apply(
            lambda x: round(x, 3)
        )
        dist = cross_section_data["Distance"]
        alti = cross_section_data["POINT_Z"]
        alti_ref = sorted(alti)
        filtrage_aires = float(self.lineEdit_filtrage_aires.text())

        # Groupement des données par transect
        grouped_data = cross_section_data.groupby("x_sec_id")
        # Initialiser une liste pour stocker les résultats par transect
        results_list = []
        # Stocker les résultats dans une liste de dictionnaires
        for x_sec_id, data_group in grouped_data:
            # Supprimer les doublons d'altitudes par transect
            unique_data_group = data_group.drop_duplicates(subset=["POINT_Z"])
            unique_data_group.reset_index(drop=True, inplace=True)

            # Récupérer les altitudes uniques après suppression des doublons ou triples
            alti = unique_data_group["POINT_Z"].values
            alti_ref = sorted(alti)
            dist = unique_data_group["Distance"].values

            # Calculer les aires pour ce transect
            areas_iteration = calculer_aire(dist, alti, alti_ref, filtrage_aires)

            # Stocker les résultats dans une liste de dictionnaires
            for (
                iteration,
                areas,
                distances,
                ref_altitude,
                intersection_indices_list,
            ) in areas_iteration:
                for i, (area, classification, ref_altitude) in enumerate(areas):
                    # Modifier le signe des aires en fonction de la classification
                    modified_area = area if classification == "above" else -area

                    # Dictionnaire pour chaque aire avec les informations requises
                    result_dict = {
                        "x_sec_id": x_sec_id,
                        "iteration": iteration,
                        "area": modified_area,
                        "distance_between_intersections": distances[i],
                        "ref_altitude": ref_altitude,
                        # 'intersection_indices': intersection_indices_list
                    }
                    results_list.append(result_dict)

        # Créer un DataFrame à partir de la liste de dictionnaires
        results_df = pd.DataFrame(results_list)
        df_output_path = os.path.join(self.directory_path, "area_trapezes.csv")
        results_df.to_csv(df_output_path, sep=",", index=False)
        print("Fichier .csv 'area_trapezes.csv' exporté avec succès.")

    # 1. Calcul de l'indicateur de profondeur hydraulique pour chaque altitude présente
    # dans la liste de référence
    def calc_prof_hydr(self):
        area_trapezes_data = pd.read_csv(
            os.path.join(self.directory_path, "area_trapezes.csv")
        )
        largest_negative_area = CalculerProfHydr(area_trapezes_data)
        output_file = os.path.join(self.directory_path, "prof_hydr.csv")
        largest_negative_area.to_csv(output_file, index=False)
        print("DataFrame exporté avec succès vers", output_file)

    def tracer_prof_hydr(self):
        # Charger les données à partir du fichier CSV
        prof_hydr_data = pd.read_csv(os.path.join(self.directory_path, "prof_hydr.csv"))

        # Vérifier si les données ont été chargées correctement
        if prof_hydr_data is None:
            print("Erreur lors de la lecture du fichier CSV.")
            return

        # Mettre à jour le graphique avec les données chargées
        scrollbar_value = self.verticalSlider_visualisation.value()

        # Calcul du nombre de graphiques visibles
        view_height = self.graphicsView_prof_hydr.height()
        graph_height = 286  # Hauteur approximative d'un graphique
        visible_graphs = max(1, int(view_height / graph_height))

        start_index = scrollbar_value
        end_index = start_index + visible_graphs

        # Grouper par 'x_sec_id'
        grouped_data = prof_hydr_data.groupby("x_sec_id")

        # Création de la scène
        scene = QtWidgets.QGraphicsScene()

        # Boucle sur les groupes de données pour créer les graphiques uniquement pour les indices visibles
        for group_name, group_data in grouped_data:
            # Vérifier si l'indice actuel est dans la plage visible
            if start_index <= group_name < end_index:
                # print("Création du graphique pour le transect", group_name)
                # Création d'un widget pour le graphique
                graph_widget = QtWidgets.QWidget()
                layout = QtWidgets.QVBoxLayout(graph_widget)

                # Création du graphique matplotlib
                fig, ax = plt.subplots()
                ref_altitude = group_data["ref_altitude"].to_numpy()
                profondeur_hydraulique = group_data["profondeur_hydraulique"].to_numpy()
                ax.scatter(ref_altitude, profondeur_hydraulique, color="blue", s=4)
                ax.set_title(
                    "Profondeur hydraulique en fonction"
                    f" de l'altitude (transect {group_name})",
                    fontsize=11,
                )
                ax.set_xlabel("Altitude (m)", fontsize=11)
                ax.set_ylabel("Profondeur Hydraulique", fontsize=11)
                ax.grid(True)
                plt.tight_layout()

                # Ajout du graphique à la scène
                layout.addWidget(FigureCanvas(fig))
                scene.addWidget(graph_widget)
                break

        # Affichage de la scène dans la QGraphicsView
        self.graphicsView_prof_hydr.setScene(scene)
        self.graphicsView_prof_hydr.fitInView(
            scene.sceneRect(), QtCore.Qt.KeepAspectRatio
        )

    # 2. Lissage de la courbe de profondeur hydraulique en fonction de la distance
    def lissage_spline(self):
        prof_hydr = pd.read_csv(
            os.path.join(self.directory_path, "prof_hydr.csv"), sep=","
        )
        deb_intervalle = float(self.lineEdit_deb_intervalle.text())
        fin_intervalle = float(self.lineEdit_fin_intervalle.text())
        pas = float(self.lineEdit_pas.text())
        test_size = float(self.lineEdit_test_size.text())
        self.spline_results = LissageCourbe(
            deb_intervalle, fin_intervalle, pas, test_size, prof_hydr
        )

    # --------------------------------------------------------------------------------
    # Méthode 1a : Amplitude de rupture de pente maximale
    # --------------------------------------------------------------------------------
    def find_bankfull_max_amplitude(self):
        bankfull_values_M1 = find_bankfull_M1(self.spline_results, self.directory_path)
        print("Altitudes de débordement:", bankfull_values_M1)

    # --------------------------------------------------------------------------------
    # Méthode 1b : Transects précédents
    # --------------------------------------------------------------------------------
    def find_banfkull_previous_transects(self):
        bankfull_values_M2 = find_bankfull_M2(self.spline_results, self.directory_path)
        print("Altitudes de débordement:", bankfull_values_M2)

    # --------------------------------------------------------------------------------
    # Méthode 2 basée sur la courbure minimale du relief
    # --------------------------------------------------------------------------------

    # 1. Détection des pic sur la courbe de courbure en fonction de la distance
    def pic_curve(self):
        curve_data = pd.read_csv(
            os.path.join(self.directory_path, "curve_data.csv"), sep=","
        )
        cross_section_data = pd.read_csv(
            os.path.join(self.directory_path, "cross_section_data.csv"), sep=","
        )
        self.transect_data = curve_Savitzky_Golay(curve_data, cross_section_data)
        print(
            "Courbe de la courbure en fonction de "
            "la distance lissée avec succès par la méthode de Savitzky-Golay."
        )

    # 2. Affichage des courbes lissées avec les divers pic sélectionnés

    def tracer_pic_curve(self):
        cross_section_data = pd.read_csv(
            os.path.join(self.directory_path, "cross_section_data.csv"), sep=","
        )
        alti_bankfull_m1 = pd.read_csv(
            os.path.join(self.directory_path, "bankfull_max_amplitude.csv"), sep=","
        )
        alti_bankfull_m2 = pd.read_csv(
            os.path.join(self.directory_path, "bankfull_previous_transects.csv"),
            sep=",",
        )

        # Mettre à jour le graphique avec les données chargées
        scrollbar_value = self.horizontalSlider_pic_curve.value()

        # Calcul du nombre de graphiques visibles
        view_height = self.graphicsView_pic_curve.height()
        graph_height = 410  # Hauteur approximative d'un graphique
        visible_graphs = max(1, int(view_height / graph_height))

        start_index = scrollbar_value
        end_index = start_index + visible_graphs

        # Création de la scène
        scene = QtWidgets.QGraphicsScene()

        # Réinitialiser la liste des points annotés
        self.annotated_points = []

        for transect_id, projected_distances, projected_altitudes in self.transect_data:
            # Vérifier si l'indice actuel est dans la plage visible
            if start_index <= transect_id < end_index:
                # Création d'un widget pour le graphique
                graph_widget = QtWidgets.QWidget()
                layout = QtWidgets.QVBoxLayout(graph_widget)

                # Création du graphique matplotlib
                fig, ax = plt.subplots(figsize=(8, 6))
                alti = cross_section_data[
                    cross_section_data["x_sec_id"] == transect_id
                ]["POINT_Z"].to_numpy()
                distance = cross_section_data[
                    cross_section_data["x_sec_id"] == transect_id
                ]["Distance"].to_numpy()
                # Tracé de la courbe de courbure et des pics détectés
                ax.plot(distance, alti, label="Profil en travers")
                ax.scatter(
                    projected_distances, projected_altitudes, color="purple", s=20
                )

                # Annoter chaque point avec un numéro unique
                for i, (dist, alt) in enumerate(
                    zip(projected_distances, projected_altitudes)
                ):
                    point_label = f"{i}"  # Unique point identifier
                    dist = round(dist, 2)
                    alt = round(alt, 2)
                    ax.annotate(
                        point_label,
                        (dist, alt),
                        textcoords="offset points",
                        xytext=(5, 5),
                        ha="center",
                        fontsize=7,
                        color="black",
                    )
                    # Ajouter le point annoté à la liste
                    self.annotated_points.append((transect_id, i, dist, alt))

                # Ajouter les lignes horizontales pour les altitudes de débordement
                bankfull_m1 = alti_bankfull_m1[
                    alti_bankfull_m1["x_sec_id"] == transect_id
                ]["altitude"].values
                bankfull_m2 = alti_bankfull_m2[
                    alti_bankfull_m2["x_sec_id"] == transect_id
                ]["altitude"].values

                if bankfull_m1.size > 0:
                    ax.axhline(
                        y=bankfull_m1[0],
                        color="r",
                        linestyle="--",
                        label="Débordement M1",
                    )
                if bankfull_m2.size > 0:
                    ax.axhline(
                        y=bankfull_m2[0],
                        color="b",
                        linestyle="-.",
                        label="Débordement M2",
                    )

                ax.set_title(
                    f"Profil en travers avec les points détectés (transect {transect_id})",
                    fontsize=11,
                )
                ax.set_xlabel("Distance (m)")
                ax.set_ylabel("Altitude (m)")
                ax.legend()
                ax.grid(False)
                plt.tight_layout()

                # Ajout du graphique à la scène
                layout.addWidget(FigureCanvas(fig))
                scene.addWidget(graph_widget)

        # Affichage de la scène dans la QGraphicsView
        self.graphicsView_pic_curve.setScene(scene)
        self.graphicsView_pic_curve.fitInView(
            scene.sceneRect(), QtCore.Qt.KeepAspectRatio
        )

        # Exporter les données conservées vers un fichier CSV
        if self.selected_points_data:  # Vérifie si des données ont été conservées
            self.exporter_dataframe_csv("selected_points_data.csv")

    # 3. Choix de l'altitude de débordement avec sélection
    # du point retenu par l'utilisateur pour chaque transect

    def conserver_point(self):
        point_index_str = self.lineEdit_id_pt_conserver.text()
        try:
            point_index = int(point_index_str)

            # Utiliser le premier transect visible comme référence
            transect_id = self.horizontalSlider_pic_curve.value()

            # Recherche du point dans la liste des points annotés
            for point in self.annotated_points:
                if point[0] == transect_id and point[1] == point_index:
                    print(
                        f"Point conservé : Transect ID = {transect_id}, Point Index = {point_index}, Distance = {point[2]}, Altitude = {point[3]}"
                    )
                    # Stocker les informations du point conservé dans la liste
                    self.selected_points_data.append(
                        {
                            "x_sec_id": transect_id,
                            "point_index": point_index,
                            "distance": point[2],
                            "altitude": point[3],
                        }
                    )
                    return

            print("Point non trouvé. Veuillez vérifier l'identifiant du point.")
        except ValueError:
            print(
                "Identifiant du point invalide. Veuillez entrer un identifiant au format correct."
            )

    def exporter_dataframe_csv(self, filename):
        # Créer un DataFrame à partir de la liste des points conservés
        df_selected_points = pd.DataFrame(self.selected_points_data)
        # Construire le chemin complet pour le fichier CSV
        filepath = os.path.join(self.directory_path, filename)
        # Exporter le DataFrame au format CSV
        df_selected_points.to_csv(filepath, index=False)

    # --------------------------------------------------------------------------------
    # Visualisation des résultats dans une fenêtre graphique
    # --------------------------------------------------------------------------------
    selected_algorithm = None

    def select_prof_hydr_max_amplitude(self):
        self.selected_algorithm = "prof_hydr_max_amplitude"
        self.visualize_final_results()

    def select_prof_hydr_previous_transects(self):
        self.selected_algorithm = "prof_hydr_previous_transects"
        self.visualize_final_results()

    def select_curvature(self):
        self.selected_algorithm = "curvature"
        self.visualize_final_results()

    def visualize_final_results(self):
        if self.selected_algorithm is None:
            # Si aucun algorithme n'est sélectionné, ne rien faire
            return
        algorithm_info = {
            "prof_hydr_max_amplitude": {
                "data_bankfull": "bankfull_max_amplitude.csv",
                "cross_section_data": "cross_section_data.csv",
                "final_results_function": self.final_results_prof_hydr,
            },
            "prof_hydr_previous_transects": {
                "data_bankfull": "bankfull_previous_transects.csv",
                "cross_section_data": "cross_section_data.csv",
                "final_results_function": self.final_results_prof_hydr,
            },
            "curvature": {
                "data_bankfull": "selected_points_data.csv",
                "cross_section_data": "cross_section_data.csv",
                "final_results_function": self.final_results_curvature,
            },
        }

        algorithm_data = algorithm_info.get(self.selected_algorithm)
        if algorithm_data:
            data_path = algorithm_data.get("data_bankfull")
            cross_section_data_path = algorithm_data.get("cross_section_data")
            final_results_function = algorithm_data.get("final_results_function")

            if data_path and cross_section_data_path:
                data_bankfull = pd.read_csv(
                    os.path.join(self.directory_path, data_path), sep=","
                )
                cross_section_data = pd.read_csv(
                    os.path.join(self.directory_path, cross_section_data_path), sep=","
                )
                final_results_function(data_bankfull, cross_section_data)

    def interpolate_coordinates(
        self, x_values, y_values, altitude_values, target_altitude
    ):
        # Effectuer l'interpolation des coordonnées x et y en fonction de l'altitude
        interpolation_function_x = interp1d(altitude_values, x_values)
        interpolation_function_y = interp1d(altitude_values, y_values)

        # Calculer les coordonnées interpolées pour l'altitude cible
        x_interpolated = interpolation_function_x(target_altitude)
        y_interpolated = interpolation_function_y(target_altitude)

        return x_interpolated, y_interpolated

    def final_results_prof_hydr(self, data_bankfull, cross_section_data):
        cross_section_data = pd.read_csv(
            os.path.join(self.directory_path, "cross_section_data.csv"), sep=","
        )

        scrollbar_value = self.horizontalSlider_final_results.value()
        view_height = self.graphicsView_prof_hydr.height()
        graph_height = 541  # Hauteur approximative d'un graphique
        visible_graphs = max(1, int(view_height / graph_height))

        start_index = scrollbar_value
        end_index = start_index + visible_graphs

        x_sec_id_unique = cross_section_data["x_sec_id"].unique()

        alti_bankfull_dict = {}

        self.pts_limites_results_list = []

        for x_sec_id in x_sec_id_unique:
            alti_bankfull_dict[x_sec_id] = data_bankfull[
                data_bankfull["x_sec_id"] == x_sec_id
            ]["altitude"].values[0]

        for group_name, group_data in cross_section_data.groupby("x_sec_id"):
            bankfull_altitude = alti_bankfull_dict[group_name]
            alti = group_data["POINT_Z"].to_numpy()
            distance = group_data["Distance"].to_numpy()

            # Trouver les coordonnées de la droite d'altitude de débordement
            river_center_distance = round(
                group_data[group_data["RivCentre"] == True]["Distance"].iloc[0], 3
            )
            bankfull_point_y = bankfull_altitude

            # Calculer les points d'intersection entre la droite et le profil
            left_intersection = None
            right_intersection = None

            # Trouver le premier point d'intersection à gauche
            for i in range(len(distance) - 1, -1, -1):
                if distance[i] < river_center_distance:
                    if alti[i] >= bankfull_point_y:
                        left_intersection = (distance[i], bankfull_point_y)
                        break

            # Trouver le premier point d'intersection à droite
            for i in range(len(distance)):
                if distance[i] >= river_center_distance:
                    if alti[i] >= bankfull_point_y:
                        right_intersection = (distance[i], bankfull_point_y)
                        break

            # Ajouter les résultats à la liste
            self.pts_limites_results_list.append(
                (group_name, left_intersection, right_intersection)
            )

        # Création de la scène
        scene = QtWidgets.QGraphicsScene()

        # Boucle sur les groupes de données pour créer
        # les graphiques uniquement pour les indices visibles
        for group_name, group_data in cross_section_data.groupby("x_sec_id"):
            # Vérifier si l'indice actuel est dans la plage visible
            if start_index <= group_name < end_index:

                graph_widget = QtWidgets.QWidget()
                layout = QtWidgets.QVBoxLayout(graph_widget)
                bankfull_altitude = alti_bankfull_dict[group_name]

                # Création du graphique
                fig, ax = plt.subplots(figsize=(8, 6))  # Taille du graphique
                alti = group_data["POINT_Z"].to_numpy()
                distance = group_data["Distance"].to_numpy()
                ax.plot(distance, alti, label="Profil en travers")
                ax.set_title(
                    f"Profil en travers avec altitude de débordement (transect {group_name})",
                    fontsize=11,
                )
                ax.set_xlabel("Distance (m)", fontsize=11)
                ax.set_ylabel("Altitude (m)", fontsize=11)
                ax.grid(False)

                # Tracer la droite d'altitude de débordement
                ax.axhline(
                    y=bankfull_altitude,
                    color="r",
                    linestyle="--",
                    linewidth=1,
                    label=f"Altitude de débordement: {bankfull_altitude:.2f}",
                )

                # Afficher les points d'intersection
                left_intersection = next(
                    (
                        item[1]
                        for item in self.pts_limites_results_list
                        if item[0] == group_name
                    ),
                    None,
                )
                right_intersection = next(
                    (
                        item[2]
                        for item in self.pts_limites_results_list
                        if item[0] == group_name
                    ),
                    None,
                )

                if left_intersection:
                    ax.plot(
                        left_intersection[0],
                        left_intersection[1],
                        "bo",
                        label="Point limite gauche",
                    )
                if right_intersection:
                    ax.plot(
                        right_intersection[0],
                        right_intersection[1],
                        "go",
                        label="Point limite droite",
                    )

                ax.legend()
                plt.tight_layout()

                # Ajouter le graphique à la scène
                layout.addWidget(FigureCanvas(fig))
                scene.addWidget(graph_widget)

        # Afficher la scène dans la QGraphicsView
        self.graphicsView_final_results.setScene(scene)
        self.graphicsView_final_results.fitInView(
            scene.sceneRect(), QtCore.Qt.KeepAspectRatio
        )

        print(self.pts_limites_results_list)

        return self.pts_limites_results_list

    def final_results_curvature(self, data_bankfull, cross_section_data):
        selected_points_data = pd.read_csv(
            os.path.join(self.directory_path, "selected_points_data.csv"), sep=","
        )

        scrollbar_value = self.horizontalSlider_final_results.value()
        view_height = self.graphicsView_prof_hydr.height()
        graph_height = 541  # Hauteur approximative d'un graphique
        visible_graphs = max(1, int(view_height / graph_height))
        start_index = scrollbar_value
        end_index = start_index + visible_graphs

        scene = QtWidgets.QGraphicsScene()

        x_sec_id_unique = cross_section_data["x_sec_id"].unique()

        alti_bankfull_dict = {}
        self.pts_limites_results_list = []

        for x_sec_id in x_sec_id_unique:
            alti_bankfull_dict[x_sec_id] = data_bankfull[
                data_bankfull["x_sec_id"] == x_sec_id
            ]["altitude"].values[0]

        for group_name, group_data in cross_section_data.groupby("x_sec_id"):
            # bankfull_altitude = alti_bankfull_dict[group_name]
            alti = group_data["POINT_Z"].to_numpy()
            distance = group_data["Distance"].to_numpy()

            # Trouver la berge la plus basse
            river_center = group_data[group_data["RivCentre"] is True]
            river_banks = group_data[group_data["RivCentre"] is False]
            mean_altitude_before = river_banks[
                river_banks["Distance"] < river_center.iloc[0]["Distance"]
            ]["POINT_Z"].mean()
            mean_altitude_after = river_banks[
                river_banks["Distance"] > river_center.iloc[0]["Distance"]
            ]["POINT_Z"].mean()

            if mean_altitude_before < mean_altitude_after:
                min_bank = "gauche"
            else:
                min_bank = "droite"

            # Déterminer la berge contenant le point sélectionné
            selected_point = selected_points_data[
                selected_points_data["x_sec_id"] == group_name
            ]
            if not selected_point.empty:
                selected_point_distance = selected_point["distance"].iloc[
                    0
                ]  # Distance du point sélectionné
                river_center_distance = river_center.iloc[0][
                    "Distance"
                ]  # Distance du centre du cours d'eau

                if selected_point_distance < river_center_distance:
                    selected_bank = "gauche"
                else:
                    selected_bank = "droite"

                # Trouver les points d'intersection gauche et droite
                left_intersection = None
                right_intersection = None

                # Trouver le premier point d'intersection à gauche
                for i in range(len(distance) - 1, -1, -1):
                    if distance[i] < river_center_distance:
                        if alti[i] >= selected_point["altitude"].iloc[0]:
                            if min_bank == "droite" or selected_bank != "gauche":
                                left_intersection = (
                                    distance[i],
                                    selected_point["altitude"].iloc[0],
                                )
                                break

                # Trouver le premier point d'intersection à droite
                for i in range(len(distance)):
                    if distance[i] >= river_center_distance:
                        if alti[i] >= selected_point["altitude"].iloc[0]:
                            if min_bank == "gauche" or selected_bank != "droite":
                                right_intersection = (
                                    distance[i],
                                    selected_point["altitude"].iloc[0],
                                )
                                break

                # Remplacer les valeurs None par les coordonnées du point rouge
                if left_intersection is None:
                    left_intersection = (
                        selected_point_distance,
                        selected_point["altitude"].iloc[0],
                    )
                if right_intersection is None:
                    right_intersection = (
                        selected_point_distance,
                        selected_point["altitude"].iloc[0],
                    )

                # Ajouter les résultats à la liste
                self.pts_limites_results_list.append(
                    (group_name, left_intersection, right_intersection)
                )

        # Boucle sur les groupes de données pour créer les graphiques uniquement pour les indices visibles
        for group_name, group_data in cross_section_data.groupby("x_sec_id"):
            # Vérifier si l'indice actuel est dans la plage visible
            if start_index <= group_name < end_index:
                # Création d'un widget pour le graphique
                graph_widget = QtWidgets.QWidget()
                layout = QtWidgets.QVBoxLayout(graph_widget)

                # Création du graphique
                fig, ax = plt.subplots(figsize=(8, 6))  # Taille du graphique
                alti = group_data["POINT_Z"].to_numpy()
                distance = group_data["Distance"].to_numpy()
                ax.plot(distance, alti, label="Profil en travers")

                # Recherche du point sélectionné pour ce transect dans self.selected_points_data
                selected_point = selected_points_data[
                    selected_points_data["x_sec_id"] == group_name
                ]
                if not selected_point.empty:
                    # Tracer le point sélectionné
                    ax.scatter(
                        selected_point["distance"],
                        selected_point["altitude"],
                        color="red",
                        s=40,
                        label="Point conservé",
                    )
                    # Tracer une droite horizontale passant par le point sélectionné
                    ax.axhline(
                        y=selected_point["altitude"].iloc[0],
                        color="red",
                        linestyle="--",
                        label=f'Altitude: {selected_point["altitude"].iloc[0]}',
                    )

                    # Tracer les points d'intersection
                    for result in self.pts_limites_results_list:
                        if result[0] == group_name:
                            left_intersection = result[1]
                            right_intersection = result[2]
                            if left_intersection:
                                ax.scatter(
                                    left_intersection[0],
                                    left_intersection[1],
                                    color="blue",
                                    s=40,
                                    label="Intersection gauche",
                                )
                            if right_intersection:
                                ax.scatter(
                                    right_intersection[0],
                                    right_intersection[1],
                                    color="green",
                                    s=40,
                                    label="Intersection droite",
                                )

                ax.set_title(
                    f"Profil en travers avec point conservé (transect {group_name})",
                    fontsize=11,
                )
                ax.set_xlabel("Distance", fontsize=11)
                ax.set_ylabel("Altitude", fontsize=11)
                ax.legend()
                ax.grid(True)
                plt.tight_layout()

                # Ajout du graphique à la scène
                layout.addWidget(FigureCanvas(fig))
                scene.addWidget(graph_widget)

        # Affichage de la scène dans la QGraphicsView
        self.graphicsView_final_results.setScene(scene)
        self.graphicsView_final_results.fitInView(
            scene.sceneRect(), QtCore.Qt.KeepAspectRatio
        )

        print(self.pts_limites_results_list)

        return self.pts_limites_results_list

    # --------------------------------------------------------------------------------------------------------
    # Calcul des points de la limite en fonction de la méthode retenue pour le choix du niveau de débordement
    # --------------------------------------------------------------------------------------------------------
    def call_coord_points_limites(self):
        pts_limites_results_list = self.pts_limites_results_list
        result = self.coord_points_limites(pts_limites_results_list)

    def coord_points_limites(self, pts_limites_results_list):
        cross_section_data = pd.read_csv(
            os.path.join(self.directory_path, "cross_section_data.csv"), sep=","
        )
        # points_limites = self.pts_limites_results_list
        # print("points limites", points_limites)
        print("Type de pts_limites_results_list:", type(pts_limites_results_list))
        print("Valeur de pts_limites_results_list:", pts_limites_results_list)
        # Liste pour stocker les coordonnées 3D interpolées
        self.coords_3D_list = []

        # Boucle pour transformer les coordonnées de chaque transect
        for transect_id, left_point, right_point in pts_limites_results_list:
            # Récupérer les données pour ce transect
            transect_data = cross_section_data[
                cross_section_data["x_sec_id"] == transect_id
            ]

            # Obtenir les coordonnées X, Y, et Z (altitude)
            distances = transect_data["Distance"].to_numpy()
            x_coords = transect_data["POINT_X"].to_numpy()
            y_coords = transect_data["POINT_Y"].to_numpy()
            altitudes = transect_data["POINT_Z"].to_numpy()

            # Fonction pour l'interpolation linéaire des coordonnées X et Y
            def interpolate_coords(distance, distances, x_coords, y_coords):
                x_interp = np.interp(distance, distances, x_coords)
                y_interp = np.interp(distance, distances, y_coords)
                return x_interp, y_interp

            # Interpoler les coordonnées pour le point limite gauche s'il existe
            if left_point:
                left_distance, left_altitude = left_point
                left_x, left_y = interpolate_coords(
                    left_distance, distances, x_coords, y_coords
                )
                self.coords_3D_list.append((left_x, left_y, left_altitude))

            # Interpoler les coordonnées pour le point limite droite s'il existe
            if right_point:
                right_distance, right_altitude = right_point
                right_x, right_y = interpolate_coords(
                    right_distance, distances, x_coords, y_coords
                )
                self.coords_3D_list.append((right_x, right_y, right_altitude))

        print(self.coords_3D_list)
        return self.coords_3D_list

    def exporter_points_limite(self):
        if self.selected_algorithm == "prof_hydr_max_amplitude":
            self.export_points_limite_prof_hydr_max_amplitude()
        elif self.selected_algorithm == "prof_hydr_previous_transects":
            self.export_points_limite_prof_hydr_previous_transects()
        elif self.selected_algorithm == "curvature":
            self.export_points_limite_curvature()

    def export_points_limites_shp(self, coords_3D_list, filename_prefix):
        # Exporter les points limites au format Shapefile
        filename = filename_prefix + ".shp"
        self.export_points_to_shapefile(coords_3D_list, filename)

    def export_points_to_shapefile(self, coords_3D_list, filename):
        # Construire le chemin complet du fichier Shapefile en utilisant os.path.join
        output_shapefile_path = os.path.join(self.directory_path, filename)

        # Créer une liste pour stocker les objets Point
        geometries = []

        # Parcourir la liste des coordonnées 3D
        for point in coords_3D_list:
            x, y, z = point
            geometries.append(Point(x, y))

        # Créer un GeoDataFrame à partir des objets Point
        gdf = gpd.GeoDataFrame(geometry=geometries)

        # Définir le système de coordonnées de référence (SCR) EPSG:3948
        crs = {"init": "epsg:3948"}

        # Exporter le GeoDataFrame au format Shapefile avec le SCR spécifié et en spécifiant le type de géométrie
        gdf.to_file(output_shapefile_path, crs=crs, geometry="Point")

        # Afficher un message de confirmation
        print(f"Fichier Shapefile exporté avec succès : {output_shapefile_path}")

        # Ajouter la couche au projet QGIS
        layer = QgsVectorLayer(
            output_shapefile_path, os.path.splitext(filename)[0], "ogr"
        )
        if not layer.isValid():
            print("La couche n'est pas valide.")
        else:
            QgsProject.instance().addMapLayer(layer)
            print(
                f"Couche {os.path.splitext(filename)[0]} ajoutée au projet avec succès"
            )

    def export_points_limite_prof_hydr_max_amplitude(self):
        # Appeler la fonction d'exportation avec les données appropriées
        filename = "points_limite_prof_hydr_max_amplitude"
        self.export_points_limites_shp(self.coords_3D_list, filename)

    def export_points_limite_prof_hydr_previous_transects(self):
        # Appeler la fonction d'exportation avec les données appropriées
        filename = "points_limite_prof_hydr_previous_transects"
        self.export_points_limites_shp(self.coords_3D_list, filename)

    def export_points_limite_curvature(self):
        # Appeler la fonction d'exportation avec les données appropriées
        filename = "points_limite_curvature"
        self.export_points_limites_shp(self.coords_3D_list, filename)
