# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
# '.\bankfull_module_JB_dialog_base_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bankfullJBDialogBase(object):
    def setupUi(self, bankfullJBDialogBase):
        bankfullJBDialogBase.setObjectName("bankfullJBDialogBase")
        bankfullJBDialogBase.resize(546, 738)
        self.verticalLayout = QtWidgets.QVBoxLayout(bankfullJBDialogBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(bankfullJBDialogBase)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Pretraitements = QtWidgets.QWidget()
        self.tab_Pretraitements.setObjectName("tab_Pretraitements")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_Pretraitements)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.tab_Pretraitements)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 1, 1, 1)
        self.lineEdit_l_transect = QtWidgets.QLineEdit(self.tab_Pretraitements)
        self.lineEdit_l_transect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_l_transect.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_l_transect.setObjectName("lineEdit_l_transect")
        self.gridLayout.addWidget(self.lineEdit_l_transect, 7, 2, 1, 1)
        self.comboBox_MNT = QtWidgets.QComboBox(self.tab_Pretraitements)
        self.comboBox_MNT.setObjectName("comboBox_MNT")
        self.gridLayout.addWidget(self.comboBox_MNT, 2, 3, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.tab_Pretraitements)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.tab_Pretraitements)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.tab_Pretraitements)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_Pretraitements)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 11, 1, 1, 3)
        self.lineEdit_e_transects = QtWidgets.QLineEdit(self.tab_Pretraitements)
        self.lineEdit_e_transects.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_e_transects.setObjectName("lineEdit_e_transects")
        self.gridLayout.addWidget(self.lineEdit_e_transects, 8, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_Pretraitements)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 1, 1, 1, 1)
        self.horizontalSlider_visualisation_transects = QtWidgets.QSlider(
            self.tab_Pretraitements
        )
        self.horizontalSlider_visualisation_transects.setMaximum(50)
        self.horizontalSlider_visualisation_transects.setOrientation(
            QtCore.Qt.Horizontal
        )
        self.horizontalSlider_visualisation_transects.setObjectName(
            "horizontalSlider_visualisation_transects"
        )
        self.gridLayout.addWidget(
            self.horizontalSlider_visualisation_transects, 13, 1, 1, 4
        )
        self.graphicsView_transects = QtWidgets.QGraphicsView(self.tab_Pretraitements)
        self.graphicsView_transects.setObjectName("graphicsView_transects")
        self.gridLayout.addWidget(self.graphicsView_transects, 12, 1, 1, 4)
        self.pushButton_CalculerCenterline = QtWidgets.QPushButton(
            self.tab_Pretraitements
        )
        self.pushButton_CalculerCenterline.setObjectName(
            "pushButton_CalculerCenterline"
        )
        self.gridLayout.addWidget(self.pushButton_CalculerCenterline, 5, 3, 1, 2)
        self.comboBox_polygon = QtWidgets.QComboBox(self.tab_Pretraitements)
        self.comboBox_polygon.setObjectName("comboBox_polygon")
        self.gridLayout.addWidget(self.comboBox_polygon, 3, 3, 1, 2)
        self.pushButton_tracer_transects = QtWidgets.QPushButton(
            self.tab_Pretraitements
        )
        self.pushButton_tracer_transects.setObjectName("pushButton_tracer_transects")
        self.gridLayout.addWidget(self.pushButton_tracer_transects, 11, 4, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_Pretraitements)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 3, 1, 1, 2)
        self.mQgsFileWidget_folder = QgsFileWidget(self.tab_Pretraitements)
        self.mQgsFileWidget_folder.setFileWidgetButtonVisible(True)
        self.mQgsFileWidget_folder.setUseLink(False)
        self.mQgsFileWidget_folder.setFullUrl(False)
        self.mQgsFileWidget_folder.setObjectName("mQgsFileWidget_folder")
        self.gridLayout.addWidget(self.mQgsFileWidget_folder, 1, 3, 1, 2)
        self.pushButton_CalculerTransects = QtWidgets.QPushButton(
            self.tab_Pretraitements
        )
        self.pushButton_CalculerTransects.setObjectName("pushButton_CalculerTransects")
        self.gridLayout.addWidget(self.pushButton_CalculerTransects, 8, 4, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_Pretraitements)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 2, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.tab_Pretraitements)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 2)
        self.pushButton_Exporter_donnees = QtWidgets.QPushButton(
            self.tab_Pretraitements
        )
        self.pushButton_Exporter_donnees.setObjectName("pushButton_Exporter_donnees")
        self.gridLayout.addWidget(self.pushButton_Exporter_donnees, 10, 4, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_Pretraitements)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 10, 1, 1, 1)
        self.tabWidget.addTab(self.tab_Pretraitements, "")
        self.tab_Courbure = QtWidgets.QWidget()
        self.tab_Courbure.setObjectName("tab_Courbure")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_Courbure)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.tab_Courbure)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.tab_Courbure)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 3)
        self.textBrowser_methodecourbure = QtWidgets.QTextBrowser(self.tab_Courbure)
        self.textBrowser_methodecourbure.setObjectName("textBrowser_methodecourbure")
        self.gridLayout_2.addWidget(self.textBrowser_methodecourbure, 2, 0, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.tab_Courbure)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.tab_Courbure)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.lineEdit_kernel = QtWidgets.QLineEdit(self.tab_Courbure)
        self.lineEdit_kernel.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_kernel.setObjectName("lineEdit_kernel")
        self.gridLayout_2.addWidget(self.lineEdit_kernel, 4, 1, 1, 1)
        self.pushButton_fit_biquadratic = QtWidgets.QPushButton(self.tab_Courbure)
        self.pushButton_fit_biquadratic.setObjectName("pushButton_fit_biquadratic")
        self.gridLayout_2.addWidget(self.pushButton_fit_biquadratic, 4, 2, 1, 1)
        self.pushButton_afficher_courbe_along_transect = QtWidgets.QPushButton(
            self.tab_Courbure
        )
        self.pushButton_afficher_courbe_along_transect.setObjectName(
            "pushButton_afficher_courbe_along_transect"
        )
        self.gridLayout_2.addWidget(
            self.pushButton_afficher_courbe_along_transect, 5, 2, 1, 1
        )
        self.label_12 = QtWidgets.QLabel(self.tab_Courbure)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 6, 0, 1, 3)
        self.label_10 = QtWidgets.QLabel(self.tab_Courbure)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 7, 0, 1, 1)
        self.lineEdit_res_mnt = QtWidgets.QLineEdit(self.tab_Courbure)
        self.lineEdit_res_mnt.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_res_mnt.setObjectName("lineEdit_res_mnt")
        self.gridLayout_2.addWidget(self.lineEdit_res_mnt, 7, 1, 1, 1)
        self.pushButton_CalculerCourbure = QtWidgets.QPushButton(self.tab_Courbure)
        self.pushButton_CalculerCourbure.setObjectName("pushButton_CalculerCourbure")
        self.gridLayout_2.addWidget(self.pushButton_CalculerCourbure, 7, 2, 1, 1)
        self.graphicsView_selected_pixels = QtWidgets.QGraphicsView(self.tab_Courbure)
        self.graphicsView_selected_pixels.setObjectName("graphicsView_selected_pixels")
        self.gridLayout_2.addWidget(self.graphicsView_selected_pixels, 8, 0, 1, 3)
        self.tabWidget.addTab(self.tab_Courbure, "")
        self.tab_Prof_Hydraulique = QtWidgets.QWidget()
        self.tab_Prof_Hydraulique.setObjectName("tab_Prof_Hydraulique")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_Prof_Hydraulique)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_24 = QtWidgets.QLabel(self.tab_Prof_Hydraulique)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 10, 0, 1, 1)
        self.pushButton_CalculerAires = QtWidgets.QPushButton(self.tab_Prof_Hydraulique)
        self.pushButton_CalculerAires.setObjectName("pushButton_CalculerAires")
        self.gridLayout_3.addWidget(self.pushButton_CalculerAires, 3, 3, 1, 1)
        self.lineEdit_pas = QtWidgets.QLineEdit(self.tab_Prof_Hydraulique)
        self.lineEdit_pas.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pas.setObjectName("lineEdit_pas")
        self.gridLayout_3.addWidget(self.lineEdit_pas, 12, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_Prof_Hydraulique)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 3, 0, 1, 2)
        self.graphicsView_prof_hydr = QtWidgets.QGraphicsView(self.tab_Prof_Hydraulique)
        self.graphicsView_prof_hydr.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded
        )
        self.graphicsView_prof_hydr.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded
        )
        self.graphicsView_prof_hydr.setInteractive(True)
        self.graphicsView_prof_hydr.setSceneRect(QtCore.QRectF(0.0, 0.0, 0.0, 0.0))
        self.graphicsView_prof_hydr.setRubberBandSelectionMode(
            QtCore.Qt.IntersectsItemShape
        )
        self.graphicsView_prof_hydr.setObjectName("graphicsView_prof_hydr")
        self.gridLayout_3.addWidget(self.graphicsView_prof_hydr, 6, 0, 1, 4)
        self.lineEdit_test_size = QtWidgets.QLineEdit(self.tab_Prof_Hydraulique)
        self.lineEdit_test_size.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_test_size.setObjectName("lineEdit_test_size")
        self.gridLayout_3.addWidget(self.lineEdit_test_size, 13, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_Prof_Hydraulique)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 2, 0, 1, 3)
        self.lineEdit_deb_intervalle = QtWidgets.QLineEdit(self.tab_Prof_Hydraulique)
        self.lineEdit_deb_intervalle.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_deb_intervalle.setObjectName("lineEdit_deb_intervalle")
        self.gridLayout_3.addWidget(self.lineEdit_deb_intervalle, 10, 1, 1, 1)
        self.lineEdit_filtrage_aires = QtWidgets.QLineEdit(self.tab_Prof_Hydraulique)
        self.lineEdit_filtrage_aires.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_filtrage_aires.setObjectName("lineEdit_filtrage_aires")
        self.gridLayout_3.addWidget(self.lineEdit_filtrage_aires, 3, 2, 1, 1)
        self.pushButton_CalculerProfHydr = QtWidgets.QPushButton(
            self.tab_Prof_Hydraulique
        )
        self.pushButton_CalculerProfHydr.setObjectName("pushButton_CalculerProfHydr")
        self.gridLayout_3.addWidget(self.pushButton_CalculerProfHydr, 4, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_Prof_Hydraulique)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 4, 0, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.tab_Prof_Hydraulique)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 3)
        self.lineEdit_fin_intervalle = QtWidgets.QLineEdit(self.tab_Prof_Hydraulique)
        self.lineEdit_fin_intervalle.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_fin_intervalle.setObjectName("lineEdit_fin_intervalle")
        self.gridLayout_3.addWidget(self.lineEdit_fin_intervalle, 11, 1, 1, 1)
        self.pushButton_Tracer_prof_hydr = QtWidgets.QPushButton(
            self.tab_Prof_Hydraulique
        )
        self.pushButton_Tracer_prof_hydr.setObjectName("pushButton_Tracer_prof_hydr")
        self.gridLayout_3.addWidget(self.pushButton_Tracer_prof_hydr, 5, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_Prof_Hydraulique)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 11, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_Prof_Hydraulique)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 9, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_Prof_Hydraulique)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 13, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_Prof_Hydraulique)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 3)
        self.label_32 = QtWidgets.QLabel(self.tab_Prof_Hydraulique)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 8, 0, 1, 4)
        self.label_15 = QtWidgets.QLabel(self.tab_Prof_Hydraulique)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 5, 0, 1, 3)
        self.pushButton_Lisser_courbes = QtWidgets.QPushButton(
            self.tab_Prof_Hydraulique
        )
        self.pushButton_Lisser_courbes.setObjectName("pushButton_Lisser_courbes")
        self.gridLayout_3.addWidget(self.pushButton_Lisser_courbes, 13, 3, 1, 2)
        self.label_34 = QtWidgets.QLabel(self.tab_Prof_Hydraulique)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 12, 0, 1, 1)
        self.verticalSlider_visualisation = QtWidgets.QSlider(self.tab_Prof_Hydraulique)
        self.verticalSlider_visualisation.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verticalSlider_visualisation.setMaximum(50)
        self.verticalSlider_visualisation.setOrientation(QtCore.Qt.Horizontal)
        self.verticalSlider_visualisation.setInvertedAppearance(True)
        self.verticalSlider_visualisation.setInvertedControls(False)
        self.verticalSlider_visualisation.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.verticalSlider_visualisation.setObjectName("verticalSlider_visualisation")
        self.gridLayout_3.addWidget(self.verticalSlider_visualisation, 7, 0, 1, 4)
        self.label_26 = QtWidgets.QLabel(self.tab_Prof_Hydraulique)
        self.label_26.setGeometry(QtCore.QRect(10, 50, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.tabWidget.addTab(self.tab_Prof_Hydraulique, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(bankfullJBDialogBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(bankfullJBDialogBase)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(bankfullJBDialogBase.accept)
        self.buttonBox.rejected.connect(bankfullJBDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(bankfullJBDialogBase)

    def retranslateUi(self, bankfullJBDialogBase):
        _translate = QtCore.QCoreApplication.translate
        bankfullJBDialogBase.setWindowTitle(
            _translate("bankfullJBDialogBase", "Dialog")
        )
        self.label_5.setText(_translate("bankfullJBDialogBase", "Pas (m) : "))
        self.label_3.setText(
            _translate("bankfullJBDialogBase", "3. Génération des transects ")
        )
        self.label_2.setText(
            _translate("bankfullJBDialogBase", "2. Calcul de la ligne centrale ")
        )
        self.label_4.setText(_translate("bankfullJBDialogBase", "Longueur (m) : "))
        self.label_31.setText(
            _translate("bankfullJBDialogBase", "5. Tracé des profils en travers")
        )
        self.label_36.setText(
            _translate("bankfullJBDialogBase", "Répertoire d'enregistrement :")
        )
        self.pushButton_CalculerCenterline.setText(
            _translate("bankfullJBDialogBase", "Calculer ")
        )
        self.pushButton_tracer_transects.setText(
            _translate("bankfullJBDialogBase", "Tracer")
        )
        self.label_29.setText(_translate("bankfullJBDialogBase", "Couche Polygone : "))
        self.pushButton_CalculerTransects.setText(
            _translate("bankfullJBDialogBase", "Calculer ")
        )
        self.label_27.setText(_translate("bankfullJBDialogBase", "Couche Raster : "))
        self.label.setText(
            _translate(
                "bankfullJBDialogBase", "1. Sélection du répertoire et des couches"
            )
        )
        self.pushButton_Exporter_donnees.setText(
            _translate("bankfullJBDialogBase", "Export des données  (.csv)")
        )
        self.label_30.setText(
            _translate(
                "bankfullJBDialogBase",
                "4. Interpolation des points le long des transects",
            )
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_Pretraitements),
            _translate("bankfullJBDialogBase", "Prétraitements"),
        )
        self.label_7.setText(
            _translate(
                "bankfullJBDialogBase", "Détermination du niveau à pleins bords "
            )
        )
        self.label_8.setText(
            _translate(
                "bankfullJBDialogBase",
                "> Méthode basée sur  la courbure minimale du relief",
            )
        )
        self.textBrowser_methodecourbure.setHtml(
            _translate(
                "bankfullJBDialogBase",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Arial'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:8.25pt; font-style:italic; color:#848484;">La méthode basée sur le calcul de la courbure minimale du relief repose sur les travaux de (Sofia et al., 2015). L\'utilisateur specifie la résolution du MNT raster ainsi que la taille de la fenêtre mobile. </span></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:8.25pt; font-style:italic; color:#848484;">La courbure est ensuite calculée pour chaque point des transects et une approche statistique QQ-plot est utilisée afin de détecter le seuil correspondant au débordement. </span></p></body></html>',
            )
        )
        self.label_11.setText(
            _translate(
                "bankfullJBDialogBase",
                "Ajustement d'une fonction biquadratique sur la surface du MNT ",
            )
        )
        self.label_9.setText(
            _translate("bankfullJBDialogBase", "Taille de la fenêtre mobile :")
        )
        self.pushButton_fit_biquadratic.setText(
            _translate("bankfullJBDialogBase", "Calculer")
        )
        self.pushButton_afficher_courbe_along_transect.setText(
            _translate("bankfullJBDialogBase", "Afficher")
        )
        self.label_12.setText(
            _translate("bankfullJBDialogBase", "Calcul de la courbure ")
        )
        self.label_10.setText(
            _translate("bankfullJBDialogBase", "Résolution du MNT (m) : ")
        )
        self.pushButton_CalculerCourbure.setText(
            _translate("bankfullJBDialogBase", "Calculer")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_Courbure),
            _translate("bankfullJBDialogBase", "Courbure "),
        )
        self.label_24.setText(_translate("bankfullJBDialogBase", "Borne inférieure :"))
        self.pushButton_CalculerAires.setText(
            _translate("bankfullJBDialogBase", "Calculer ")
        )
        self.label_20.setText(
            _translate("bankfullJBDialogBase", "Critère de filtrage des aires (m²) : ")
        )
        self.pushButton_CalculerProfHydr.setText(
            _translate("bankfullJBDialogBase", "Calculer ")
        )
        self.label_28.setText(
            _translate(
                "bankfullJBDialogBase", "2. Calcul de la prodondeur hydraulique : "
            )
        )
        self.label_13.setText(
            _translate(
                "bankfullJBDialogBase", "Détermination du niveau à pleins bords "
            )
        )
        self.pushButton_Tracer_prof_hydr.setText(
            _translate("bankfullJBDialogBase", "Tracer")
        )
        self.label_33.setText(_translate("bankfullJBDialogBase", "Borne supérieure :"))
        self.label_22.setText(
            _translate("bankfullJBDialogBase", "Valeurs de s à tester : ")
        )
        self.label_23.setText(_translate("bankfullJBDialogBase", "Ensemble de test : "))
        self.label_14.setText(
            _translate(
                "bankfullJBDialogBase", "> Méthode basée sur  la profondeur hydraulique"
            )
        )
        self.label_32.setText(
            _translate(
                "bankfullJBDialogBase",
                "3. Lissage de la courbe de prodondeur hydraulique en fonction",
                "de l'altitude : ",
            )
        )
        self.label_15.setText(
            _translate("bankfullJBDialogBase", "Visualisation des résultats :")
        )
        self.pushButton_Lisser_courbes.setText(
            _translate("bankfullJBDialogBase", "Lissage")
        )
        self.label_34.setText(_translate("bankfullJBDialogBase", "Pas  : "))
        self.label_26.setText(
            _translate(
                "bankfullJBDialogBase", "1. Calcul de l'aire de la section mouillée :"
            )
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_Prof_Hydraulique),
            _translate("bankfullJBDialogBase", "Profondeur hydraulique"),
        )
        self.label_16.setText(
            _translate(
                "bankfullJBDialogBase", "Méthode basée sur la profondeur hydraulique"
            )
        )
        self.label_17.setText(_translate("bankfullJBDialogBase", "RMSE point cloud "))
        self.label_18.setText(_translate("bankfullJBDialogBase", "RMSE DTM"))
        self.label_19.setText(_translate("bankfullJBDialogBase", "RMSE fitting"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2),
            _translate("bankfullJBDialogBase", "Analyse de précision"),
        )


from qgsfilewidget import QgsFileWidget
